---
title: "SDJR and MLRA Summary"
author: "`r Sys.getenv('USERNAME')`"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
suppressWarnings( {
  library(soilDB)
  library(tidyverse)
  library(viridis)
  library(sp)
  library(sf)
  library(knitr)
  })
```


```{r load}
options(stringsAsFactors = FALSE)

ownCloud <- "C:/Users/stephen.roecker/ownCloud/data/lims_data/"
ro <- 11
eval_mlra_initial <- c("SDJR (Obsolete)", "MLRA", "INITIAL", "EVAL")
eval_mlra <- c("SDJR (Obsolete)", "EVAl", "MLRA")
eval <- c("SDJR (Obsolete)", "EVAL")
pt_all <- c("CORR (Obsolete)", "DSP", "ES", "EVAL", "INITIAL", "JOIN (Obsolete)", "MLRA", "NEON", "SCS (Obsolete)", "SDJR (Obsolete)",  "SH (Obsolete)", "SPATIAL EDIT", "SPECIAL", "TABULAR EDIT", "TRADITIONAL (Obsolete)")
  

# progress
p <- expand.grid(mlrassoarea      = paste0(1:12, "-%"),
                 fy               = 2012:2017,
                 projecttypename  = "%25",
                 stringsAsFactors = FALSE
                 )
prg <- {
  split(p, list(p$mlrassoarea, p$fy, p$projecttypename), drop = TRUE) ->.;
  lapply(., function(x) {
    cat("procressing", paste(x$mlrassoarea, x$fy, x$projecttypename), "\n")
    get_progress_from_LIMS(x$mlrassoarea, x$fy, x$projecttypename)
    }) ->.;
  do.call("rbind", .)
  }

fname <- paste0(ownCloud, "lims_goal_", "2017-12-20_us_2012_2017", ".csv")
# write.csv(prg, file = fname, row.names = FALSE)
prg <- read.csv(file = fname)


# project

p <- expand.grid(mlrassoarea      = paste0(1:12, "-%"),
                 fy               = 2012:2017,
                 stringsAsFactors = FALSE
                 )
prj <- {
  split(p, list(p$mlrassoarea, p$fy), drop = TRUE) ->.;
  lapply(., function(x) {
    cat("procressing", paste(x$mlrassoarea, x$fy), "\n")
    get_project_from_LIMS(x$mlrassoarea, x$fy)
    }) ->.;
  do.call("rbind", .)
  }

fname <- paste0(ownCloud, "lims_project_", "2017-12-20_us_2012_2017", ".csv")
# write.csv(prj, file = fname, row.names = FALSE)
prj <- read.csv(file = fname)


# reverse correlation

mlrassoarea <- paste0("11-", c("ATL", "AUR", "CLI", "FIN", "GAL", "IND", "JUE", "MAN", "SPR", "UNI", "WAV"))

p <- expand.grid(mlrassoarea = paste0(1:12, "-%"),
                 fy          = 2012:2017,
                 projectname = "%",
                 stringsAsFactors = FALSE
                 )
rcor <- {
  split(p, list(p$mlrassoarea, p$fy, p$projectname), drop = TRUE) ->.;
  lapply(., function(x) {
    cat("procressing", paste(x$mlrassoarea, x$fy, x$projectname), "\n")
    get_reverse_correlation_from_LIMS(x$mlrassoarea, x$fy, x$projectname)
    }) ->.;
  do.call("rbind", .)
  }

fname <- paste0(ownCloud, "lims_reverse_correlation_fy_", "2017-12-20_us_2012_2017.csv")
# write.csv(rcor, file = fname, row.names = FALSE)
rcor <- read.csv(file = fname)

```


## Estimate Workload

```{r workload, eval=FALSE}

fte <- data.frame(
  fte = c(2, 2.5, 3, 2.5, 3, 5, 3, 5, 4, 1, 3),
  office = c("11-ATL", "11-AUR", "11-CLI", "11-FIN", "11-GAL", "11-IND", "11-JUE", "11-MAN", "11-SPR", "11-UNI", "11-WAV")
  ) # these numbers need to be updated to reflect retirements
wdays <- (52*5-10-3*5)*.75 # 52 weeks per year, 5 days per week, minus 10 holidays, minus 3 weeks vaction, at 75% an individuals time (i.e. minus 15% for TSS and 10% for miscellaneous)
# projects per person = 69 projects/ 3.5 fte
# days per project = workingdays/projects per person 

days_p_person <- function(days, projects, fte){
  days/(projects/fte)
}

goals_test <- mutate(goals,
                     mapunit = ifelse(projectname %in% c("^SDJR"), projectname, NA),
                     mapunit = sapply(projectname, function(x) unlist(strsplit(x, " - "))[3]),
                     components = sapply(mapunit, function(x) unlist(strsplit(x, " "))[1])
                     )

test <- goals_test %>%
  filter(region %in% ro) %>%
  group_by(fy = as.character(fy), office) %>%
  summarize(
    acres = sum(reported),
    n_projects = length(unique(projectname)),
    n_mapunits = length(unique(mapunit)),
    n_majors = length(unique(sapply(components, function(x) unlist(strsplit(x, "-"))[1])))
    ) %>% 
  inner_join(fte, by = "office")

test <- mutate(test,
               fte = round(fte, 1),
               days = round(fte*wdays, 0),
               days_project_fte = round(days / (n_projects / fte), 0), days_major_fte = round(days / (n_majors / fte), 0)
               ) %>%
  as.data.frame()
test2 <- rbind(test, c("2012:2016", "Average",
                       round(apply(test[3:9], 2, mean), 0))
               )

kable(test2)

# ggplot(test, aes(x = days_project_fte, y = acres, group = office)) +
#   geom_point() +
#   facet_wrap(fy ~ ., scales = "free_y")
```


## Examine muacres != acre_landcat

```{r, eval=FALSE}

prj <- within(prj, {
  acre_diff = muacres - acre_landcat
  acre_g20  = muacres * 0.2
  })

View(test <- subset(prj, projecttypename != "ES" & 
                      n_spatial < 1 & 
                      muacres != acre_landcat & 
                      fiscalyear == 2017
                    ))

test2 <- get_projectmapunit_from_NASIS()
test3 <- subset(test2, projectname == "SDJR - MLRA 111B - Pewamo silty clay loam, 0 to 2 percent slopes" & mustatus == "additional")
sum(test3["muacres"])

```


## Region 11 Acres

```{r goals, fig.height=8, fig.width=8}
brks <- c(0, 2e5, 5e5, 1e6, 5e6)
lbls <- c("200k", "500k", "1000k", "5000k")

prg_sub <- prg %>%
  mutate(projecttypename = gsub(" \\(Obsolete\\)", "", projecttypename),
         region          = factor(gsub("-", "", substr(mlrassoarea, 1, 2)), levels = 1:12),
         muacres_t       = cut(muacres, breaks = brks, labels = lbls)
         ) %>%
  filter(! projecttypename %in% c("ALL PROJECTS"))

regions <- prg_sub %>%
  group_by(region, projecttypename, fiscalyear) %>%
  summarize(mlrassoarea     = as.character(region[1]),
            n_project       = sum(n_project, na.rm = TRUE),
            n_areasymbol    = sum(n_areasymbol, na.rm = TRUE),
            n_nationalmusym = sum(n_nationalmusym, na.rm = TRUE),
            n_spatial       = sum(n_spatial, na.rm = TRUE),
            acre_progress   = sum(acre_progress, na.rm = TRUE)
            ) %>%
  mutate(acre_progress_t = cut(acre_progress, breaks = brks, labels = lbls))

r11 <- filter(regions, 
              region == 11
              )[-1]

r11_sso <- filter(prg_sub, 
                  region == 11
                  ) %>%
  mutate(acre_progress_t = cut(acre_progress, 
                               breaks = brks, 
                               labels = lbls)
         ) %>%
  select(mlrassoarea, projecttypename, fiscalyear, n_project, n_areasymbol, n_nationalmusym, n_spatial, acre_progress, acre_progress_t)

r11_all <- rbind(r11, r11_sso)
r11_all <- mutate(r11_all,
                  n_project_t = cut(r11_all$n_project,
                           breaks = c(0, 1, 5, 15, 35, 50, 100),
                           labels = c("1", "5", "15", "35", "50", "100+")
                           ),
                  mlrassoarea = factor(mlrassoarea)
                  )


# line plot of region 11 acres
filter(r11_all, projecttypename != "ES") %>%
ggplot(aes(x = fiscalyear, y = acre_progress, color = projecttypename)) + 
  geom_line(lwd = 1) +
  geom_point(cex = 2) +
  facet_wrap(~ mlrassoarea, scales = "free_y", ncol = 1, strip.position = "right") +
  scale_x_continuous(breaks = seq(2012, 2017, 2)) +
  ggtitle("Region 11 Acre Progress") + ylab("acres") + xlab("fiscal year")


# dotplot of region 11 acres
filter(r11_all, mlrassoarea != 11 & projecttypename %in% eval_mlra) %>% 
  mutate(mlrassoarea = factor(mlrassoarea, levels = rev(levels(mlrassoarea)))) %>%
ggplot(aes(x = acre_progress, y = mlrassoarea)) + 
  geom_point() + 
  facet_grid(projecttypename ~ fiscalyear, scales = "free_x") +
  ggtitle("Dotplot of Acres Reported by Fiscal Year and Project Type")


# plot of region 11 number of projects
filter(r11_all, mlrassoarea != 11 & projecttypename %in% eval_mlra) %>%
ggplot(aes(x = n_nationalmusym, y = n_project)) + 
  geom_text(aes(label = mlrassoarea), size = 2) +
  facet_wrap(~ projecttypename + fiscalyear, scales = "free", nrow = 4) +
  theme(aspect.ratio = 1) +
  ggtitle("Region 11 Projects")

```


## SSD Acres

```{r, eval=FALSE}

# plot of all regions
filter(regions, projecttypename %in% c("SDJR", "MLRA", "INITIAL") & fiscalyear %in% 2012:2017) %>%
ggplot(aes(x = fiscalyear, y = acre_progress, color = projecttypename)) +   geom_line(lwd = 1) +
  geom_point(cex = 2) +
  facet_wrap(~ region, scales = "free_y", ncol = 1, strip.position = "right") +
  scale_x_continuous(breaks = seq(2012, 2017, 2)) +
  ggtitle("SSD Acre Progress") + ylab("Acres") + xlab("Fiscal Year")


# dotplot of all regions acres
filter(regions, projecttypename %in% c("SDJR", "MLRA", "INITIAL") & fiscalyear %in% 2012:2017) %>% 
  mutate(mlrassoarea = factor(mlrassoarea, 
                              levels = rev(1:12))
         ) %>%
ggplot(aes(x = acre_progress, y = mlrassoarea)) + 
  geom_point() + 
  facet_grid(projecttypename ~ fiscalyear, scales = "free_x") +
  ggtitle("SSD of Acres Reported by Fiscal Year and Project Type") + ylab("Regions") + xlab("Acres")


# plot of all regions number of projects
filter(regions, projecttypename %in% c("SDJR", "INITIAL", "MLRA") & fiscalyear %in% 2012:2017) %>%
ggplot(aes(x = n_nationalmusym, y = n_project)) + #, size = acre_progress)) + 
  geom_text(aes(label = region),size = 4) +
  facet_wrap(projecttypename ~ fiscalyear, scale = "free", nrow = 3) +
  theme(aspect.ratio = 1) +
  ggtitle("Scatter Plot of Regions") + ylab("Number of Projects") + xlab("Number of Map Units")


# plot of all regions number of spatial changes
filter(regions, projecttypename %in% c("SDJR", "MLRA")) %>%
ggplot(aes(x = n_spatial, y = n_areasymbol)) + 
  geom_text(aes(label = region), cex = 4) +
  facet_wrap(~ projecttypename + fiscalyear, scales = "free", nrow = 2) +
  theme(aspect.ratio = 1) +
  ggtitle("SSD Spatial Changes")
```


## Compare muacres to Goaled Acres

```{r compare}

rcor_g <- group_by(rcor, mlrassoarea, projecttypename, fiscalyear, projectiid, projectname) %>% 
  summarize(sum_muacres = sum(muacres, na.rm = TRUE),
            sum_new_muacres = sum(new_muacres, na.rm = TRUE),
            n_spatial = sum(spatial_change, na.rm = TRUE)
            ) %>% 
  filter(grepl(ro, mlrassoarea))

test <- left_join(prj, rcor_g, by = "projectiid", all.x = TRUE)
test_sub <- filter(test,
                   muacres != sum_muacres &
                   n_spatial.y < 1 &
                   projecttypename.x != "ES"
                   ) %>%
  select(mlrassoarea.x, projectname.x, n_spatial.y, muacres, sum_muacres, sum_new_muacres, acre_goal)

```


## Summarize Spatial Changes

```{r spatial}

# compare rcor to prj

rcor_sum <- group_by(rcor, mlrassoarea, projecttypename, fiscalyear, projectiid, projectname) %>% 
  summarize(n_spatial = sum(spatial_change, na.rm = TRUE))
prj_sub <- filter(prj, fiscalyear == 2018 & projectapprovedflag == TRUE)

test <- left_join(prj, rcor_sum, by = "projectiid")

View(test2 <- filter(test, n_spatial.y > 0 & n_spatial.x < 1))


# plot comparison

r11_spatial <- rcor %>%
  filter(grepl(ro, mlrassoarea) & spatial_change == TRUE & projecttypename %in% eval_mlra) %>%
  group_by(fiscalyear, projecttypename, mlrassoarea) %>% 
    summarize(
      acres = sum(muacres, na.rm = TRUE),
      n_areasymbol = length(unique(areasymbol)),
      n_nationalmusym = length(unique(nationalmusym))
      ) %>%
  arrange(desc(acres)) %>%
  as.data.frame()

filter(r11_spatial, fiscalyear %in% 2012:2017) %>%
ggplot(aes(x = n_nationalmusym, y = n_areasymbol)) + 
  geom_text(aes(label = mlrassoarea), cex = 2.5) +
  facet_wrap(~ paste(projecttypename, "-", fiscalyear), scales = "free") +
  theme(aspect.ratio = 1) +
  ggtitle("Region 11 Spatial Changes")
```


## Map Progress by AREASYMBOL (ggplot2)

```{r map_as, fig.height=10, fig.width=8, eval=TRUE}

# correct muacres for goal percent = acre_progress / acre_landcat
vars <- c("projectiid", "fiscalyear", "acre_landcat", "acre_progress")
rcor2 <- left_join(rcor, prj[vars], by = c("projectiid", "fiscalyear")) %>%
  filter(musym != "NOTCOM")
rcor3 <- mutate(rcor2,
                muacres  = ifelse(is.na(muacres), new_muacres, muacres),
                acre_pct = acre_progress / acre_landcat,
                acre_pct = ifelse(acre_pct > 0.01, round(acre_pct, 2), acre_pct),
                acre_pct = ifelse(acre_pct > 100, 100, acre_pct),
                muacres2  = muacres * acre_pct
                )
# filter out records for non-INITIAL projects
rcor4 <- filter(rcor3, 
                ! projecttypename %in% c("INITIAL", "TRADITIONAL (Obsolete)") &
                is.na(nonmlrassaarea)
                )

# aggregate muacres by areasymbol for non-INITIAL projects
rcor_as1 <- rcor4 %>%
  filter(#grepl(ro, mlrassoarea) &
         projecttypename != "ES" &
         fiscalyear %in% 2012:2017
         ) %>%
  group_by(mlrassoarea, projecttypename, fiscalyear, projectiid, projectname, areasymbol) %>%
  summarize(
    muacres     = sum(muacres2   , na.rm = TRUE),
    new_muacres = sum(new_muacres, na.rm = TRUE)
    ) %>%
  group_by(fiscalyear, areasymbol) %>%
  summarize(
    muacres     = sum(muacres    , na.rm = TRUE),
    new_muacres = sum(new_muacres, na.rm = TRUE)
    ) %>%
  as.data.frame()
# INITIAL projects
rcor_as2 <- filter(prj,
                   projecttypename %in% c("INITIAL", "TRADITIONAL (Obsolete)") &
                   ! is.na(nonmlrassaarea)
                   ) %>%
  select(fiscalyear, nonmlrassaarea, acre_progress) %>%
  rename(areasymbol = nonmlrassaarea, muacres = acre_progress) %>%
  mutate(new_muacres = 0)
rcor_as <- rbind(rcor_as1, rcor_as2)
rcor_as <- group_by(rcor_as, fiscalyear, areasymbol) %>%
  summarize(
    muacres     = sum(muacres    , na.rm = TRUE),
    new_muacres = sum(new_muacres, na.rm = TRUE)
    ) %>%
  filter(areasymbol != "")

rcor_as$acres <- cut(rcor_as$muacres, 
                     breaks = c(0, 10000, 50000, 100000, 500000, 1000000), 
                     labels = c("0-10k", "10-50k", "50-100k", "100-500k", "500k-1000k")
                     )

rcor_as_w <- select(rcor_as, fiscalyear, areasymbol, acres) %>% 
  spread(fiscalyear, acres) # spread recycles non-grouping variables, so it needs to be combined with select, reshape() silently drops them but gives a warning if they vary

params <- expand.grid(fiscalyear = 2012:2017,
                      areasymbol = sort(unique(rcor_as$areasymbol)),
                      stringsAsFactors = FALSE
                      )
rcor_as_l <- left_join(params, rcor_as, by = c("fiscalyear", "areasymbol"))


# load spatial data
ssa_sf <- read_sf(dsn = "D:/geodata/soils/soilsa_a_nrcs.shp", layer = "soilsa_a_nrcs")
ssa_sf <- st_transform(ssa_sf, crs = "+init=epsg:5070")
data(state)
st <- state.abb[-c(11, 2)]
ssa_sf$state <- substr(ssa_sf$areasymbol, 1, 2)
ssa_sf <- ssa_sf[ssa_sf$state %in% st, ]
# ssa_sf <- read_sf(dsn = "M:/geodata/soils/SSURGO_CONUS_FY2016.gdb", layer = "SAPOLYGON")
# names(ssa_sf)[c(1, 6)] <- c("areasymbol", "geometry")
# st_crs(ssa_sf) <- "+init=epsg:5070"
states <- read_sf(dsn = "D:/geodata/government_units/state_nrcs_a_mbr.shp", layer = "state_nrcs_a_mbr")
states <- st_transform(states, crs = "+init=epsg:5070")

ssa_w <- inner_join(ssa_sf, rcor_as_w, by = "areasymbol")
ssa_l <- inner_join(ssa_sf, rcor_as_l, by = "areasymbol")


# ggplot2 (requires github version)

# acres_gg <- 
# 
acres_gg <- # filter(ssa_l, grepl("OH", areasymbol)) %>% 
  ggplot(ssa_l) +
  geom_sf(aes(fill = acres, linetype = NA)) +
  scale_fill_viridis(discrete = TRUE) +
  facet_wrap(~ fiscalyear) +
  ggtitle("Time Series of Reported Acres by County")
acres_gg <- acres_gg +
  geom_sf(data = states, aes(fill = NA))

png(file = "acres_gg2.png", width = 17, height = 11, units = "in", res = 400)
plot(acres_gg)
dev.off()

```


## Map Progress by AREASYMBOL (spplot)

```{r, eval=FALSE}
# spplot example

idx <- names(ssa_w) %in% 2012:2017
names(ssa_w)[idx] <- paste0("FY", names(ssa_w)[idx]) 
ssa_w_sp <- as(ssa_w, "Spatial")

bb <- bbox(ssa_w_sp)
# ssa3$state <- substr(ssa_sf$areasymbol, 1, 2)
# st <- toupper(c("ia", "il", "in", "mn", "mo", "wi"))
# st_sub <- filter(ssa3, state %in% st) %>% select(FY2012, FY2013, FY2014, FY2015, FY2016, FY2017))

spplot(ssa_w_sp, paste0("FY", 2012:2017),
       main = "Time Series of Updated Acres by County",
       xlim = bb[1, ] + c(-0.2, 0.2), ylim = bb[2, ] + c(-0.2, 0.2),
       as.table = TRUE,
       colorkey = list(space = "right"), #, height = 1),
       scales = list(draw = TRUE, alternating = FALSE)
       )
```


## Summarize and plot acres by musym

```{r map_musym, eval=FALSE, echo=FALSE, eval=FALSE}
corrs_mukey <- ddply(corrs, .(fy, region), summarize, MUKEY = unique(new_mukey))
corrs_ssaMusym <- ddply(corrs, .(fy, region), summarize, MUKEY = unique(paste0(areasymbol,"_", old_musym)))

fy12 <- subset(corrs_mukey, fy == 2012 & region == 11)
fy13 <- subset(corrs_ssaMusym, fy == 2013 & region == 11); 
fy14 <- subset(corrs_mukey, fy == 2014 & region == 11)
fy15 <- subset(corrs_mukey, fy == 2015 & region == 11)

fy13_r <- raster("M:/geodata/soils/gssurgo_fy13_250m.tif")
fy13_r_dbf <- read.dbf("M:/geodata/soils/gssurgo_fy13_30m.tif.vat.dbf")
fy13_r <- ratify(fy13_r, count=TRUE)
rat <- levels(fy13_r)[[1]]
names(fy13_r_dbf)[1] <- "ID"
names(fy13_r_dbf)[3] <- "MUKEY"
rat_new <- join(rat, fy13_r_dbf, type = "left", by = "ID")
rat_new <- join(rat_new, fy13, type = "left", by = "MUKEY")
fy13_r_2 <- fy13_r
levels(fy13_r_2) <- rat_new
# fy13_r_new <- deratify(fy13_r_2, att='fy', filename='gSSURGO_fy13_progress.tif', overwrite=TRUE, datatype='INT4U', format='GTiff', progress = "text")


fy14_r <- raster("M:/geodata/soils/gssurgo_fy14_250m.tif")
fy14_r_dbf <- read.dbf("M:/geodata/soils/gssurgo_fy14_30m.tif.vat.dbf")
fy14_r <- ratify(fy14_r, count=TRUE)
rat <- levels(fy14_r)[[1]]
names(fy14_r_dbf)[1] <- "ID"
rat_new <- join(rat, fy14_r_dbf, type = "left", by = "ID")
rat_new <- join(rat_new, fy14, type = "left", by = "MUKEY")
fy14_r_2 <- fy14_r
levels(fy14_r_2) <- rat_new
# fy14_r_new <- deratify(fy14_r_2, att='fy', filename='gSSURGO_fy14_progress.tif', overwrite=TRUE, datatype='INT4U', format='GTiff', progress = "text")


fy15_r <- raster("M:/geodata/soils/gssurgo_fy15_250m.tif")
fy15_r_dbf <- read.dbf("M:/geodata/soils/gssurgo_fy15_30m.tif.vat.dbf")
fy15_r <- ratify(fy15_r, count=TRUE)
rat <- levels(fy15_r)[[1]]
names(fy15_r_dbf)[1] <- "ID"
rat_new <- join(rat, fy15_r_dbf, type = "left", by = "ID")
rat_new <- join(rat_new, fy15, type = "left", by = "MUKEY")
levels(fy15_r) <- rat_new
# fy15_r_new <- deratify(fy15_r, att='fy', filename='gSSURGO_fy15_progress.tif', overwrite=TRUE, datatype='INT4U', format='GTiff', progress = "text")

fy13_r_new <- raster("C:/workspace/gSSURGO_fy13_progress.tif")
fy14_r_new <- raster("C:/workspace/gSSURGO_fy14_progress.tif")
fy15_r_new <- raster("C:/workspace/gSSURGO_fy15_progress.tif")
ssa <- readOGR(dsn = "M:/geodata/soils/soilsa_a_nrcs.shp", layer = "soilsa_a_nrcs", encoding = "ESRI Shapefile")
ssa <- spTransform(ssa, CRS("+init=epsg:5070"))
ssa$state <- substr(ssa$areasymbol, 1, 2)
wi <- subset(ssa, state == "WI")
test <- stack(fy13_r_new, fy14_r_new, fy15_r_new)
names(test) <- c("FY13_SDJR_Progress", "FY14_SDJR_Progress", "FY15_SDJR_Progress")
spplot(test, sp.layout = wi, maxpixels = 5000000, xlim = bbox(wi)[1, ], ylim = bbox(wi)[2, ], colorkey = FALSE, col.regions = "blue", strip = strip.custom(bg = grey(0.85)))

test_f <- function(x) test = unique(x)

test <- by(corrs, corrs[c("fy", "region")], function(x) cbind(unique(x$new_mukey), unique(x$old_mukey)))
test2 <- cbind(expand.grid(dimnames(test)), do.call(rbind, test))
```
