---
title: "SSURGO QA Report"
author: "`r Sys.getenv('USERNAME')`"
date: "`r Sys.Date()`"
output: html_document
params:
  fy:          !r as.numeric(2018)
  region:      !r as.numeric(11)
  ssoffice:    !r as.character("11-FIN;12-GRR") # 11-AUR;11-ATL;11-FIN;11-GAL;11-IND;11-JUE;11-MAN;11-UNI;11-SPR;11-WAV")
  projectname: !r as.character("%")
  mupolygon:   !r as.character("G:geodata/project_data/FY2018_EXPORT/mupolygon_11FIN_edit_v2.dbf")
  owners:      !r as.character("C:/workspace2/github/SSURGO-QA/trunk/SSURGO_Soil_Survey_Area.gdb")
  ownCloud:    !r as.character("C:/Users/stephen.roecker/ownCloud/data/lims_data/")
  local:       !r as.logical(FALSE)
editor_options: 
  chunk_output_type: console
---


# Report of changes requiring SSURGO recertification

```{r parameters, echo=FALSE, warning=FALSE, message=FALSE}

# These figures don't compare with Alena's spreadsheets. Her spreadsheets have additional counties that aren't captured in the Project Record.
# This assumes no changes have been made to the ORIG columns, could run Alena's qa against an unedited copy.

library(soilDB)
library(dplyr)
library(DT)

# params <- data.frame(
#   fy          =  2018,
#   region      =  11,
#   ssoffice    = "11-FIN;12-FLI",  # 11-AUR;11-ATL;11-FIN;11-GAL;11-IND;11-JUE;11-MAN;11-UNI;11-SPR;11-WAV");
#   projectname = "%",
#   mupolygon   = "M:geodata/project_data/FY2018/mupolygon_11MAN_edit.dbf",
#   owners      = "C:/workspace2/github/SSURGO-QA/trunk/SSURGO_Soil_Survey_Area.gdb",
#   ownCloud    = "C:/Users/stephen.roecker/ownCloud/data/lims_data/",
#   local       = FALSE,
#   stringsAsFactors = FALSE
#   )

attach(params)
ssoffice <- unlist(strsplit(params$ssoffice, ";"))

mupolygon <- foreign::read.dbf(mupolygon, as.is = TRUE)
names(mupolygon) <- tolower(names(mupolygon))
owners <- sf::read_sf(dsn = owners, layer = "SSA_Regional_Ownership_Master", stringsAsFactors = FALSE)
class(owners) <- "data.frame"
```

```{r load-goals, echo=FALSE, warning=FALSE, message=FALSE}

# project goals

p <- expand.grid(mlrassoarea      = ssoffice,
                 fy               = fy,
                 stringsAsFactors = FALSE
                 )
prj <- {
  split(p, list(p$mlrassoarea, p$fy), drop = TRUE) ->.;
  lapply(., function(x) {
    cat("procressing", paste(x$mlrassoarea, x$fy), "\n")
    get_project_from_NASISWebReport(x$mlrassoarea, x$fy)
    }) ->.;
  do.call("rbind", .) ->.;
  row.names(.) <- 1:nrow(.)
  . ->.;
  }

# fname <- paste0(ownCloud, "nwr_project_fy", fy, "_2018_08_21.csv")
# write.csv(prj, file = fname, row.names = FALSE)
# prj <- read.csv(file = fname, stringsAsFactors = FALSE)
```


```{r load-pcor, echo=FALSE, warning=FALSE, message=FALSE}
# project correlation

p <- expand.grid(mlrassoarea = ssoffice,
                 fy          = fy,
                 projectname = projectname,
                 stringsAsFactors = FALSE
                 )
pcor <- {
  split(p, p[c("mlrassoarea", "fy", "projectname")], drop = TRUE) ->.;
  lapply(., function(x) {
    cat("getting the project correlation for ", x$mlrassoarea, "and", x$fy, "from NASISWebReport \n")
    get_project_correlation_from_NASISWebReport(x$mlrassoarea, x$fy, x$projectname)
  }) ->.;
  do.call("rbind", .) ->.;
  row.names(.) <- 1:nrow(.)
  . ->.;
  }

# fname <- paste0(ownCloud, "nwr_project_correlation_fy", fy, "_2018_08_15.csv")
# write.csv(pcor, fname, row.names = FALSE)
# pcor <- read.csv(fname, stringsAsFactors = FALSE)
```

```{r load-legends, echo=FALSE, warning=FALSE, message=FALSE}
# correlated mapunits (aka legend)

asym <- subset(owners, AREASYMBOL %in% sort(unique(pcor$areasymbol[pcor$mlrassoarea %in% ssoffice])), select = AREASYMBOL)

if (local == TRUE) {
         leg  <- get_mapunit_from_NASIS(SS = FALSE)
  } else leg  <- get_mapunit_from_NASISWebReport(asym$AREASYMBOL)

# fname <- paste0(ownCloud, "nwr_mapunits_fy", fy, "_2018_08_15.csv")
# write.csv(leg, fname, row.names = FALSE)
# leg <- read.csv(fname, stringsAsFactors = FALSE)

```


```{r, summarize geodatabase tabular changes, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}

# WEB-MLRA_Goals_Progress

goals_summary <- prj %>%
  filter(mlrassoarea %in% ssoffice &
         acre_goal > 0
         ) %>%
  group_by(mlrassoarea, projecttypename) %>%
  summarise(
    n_projects    = length(unique(projectname)),
    acre_goal     = sum(acre_goal, na.rm = TRUE), 
    acre_progress = sum(acre_progress, na.rm = TRUE),
    pct_progress  = round(acre_progress/ acre_goal * 100)
    )
datatable(goals_summary, caption = "Table 1: Number or SDJR projects per SS Office")


# Correlation report (completed spatial changes in NASIS)

pcor_sub <-subset(pcor, mlrassoarea %in% ssoffice & (!is.na(new_musym) | pmu_seqnum == 2018))

pcor_summary <- pcor_sub %>%
  group_by(mlrassoarea, projecttypename) %>%
  summarise(
    n_projects = length(unique(projectiid)),
    acre_goal  = ifelse(unique(projecttypename) == "EVAL", 
                        sum(muacres, na.rm = TRUE) * 0.5,
                        sum(muacres, na.rm = TRUE)
                        )
    )
datatable(pcor_summary, caption = "Table 2: Completed EVAL & MLRA Summary")


pcor_summary <- pcor_sub %>%
  filter(
    spatial_change == TRUE
    ) %>%
  group_by(mlrassoarea, projecttypename) %>%
  summarise(
    n_projects   = length(unique(projectiid)),
    n_areasymbol = length(unique(areasymbol)),
    n_mukey      = length(unique(mukey)),
    acre_goal  = ifelse(unique(projecttypename) == "EVAL", 
                        sum(muacres, na.rm = TRUE) * 0.5,
                        sum(muacres, na.rm = TRUE)
                        ),
    acre_goal  = ifelse(unique(projecttypename) == "SPATIAL EDIT",
                        sum(muacres) * 0.25,
                        muacres
                        )
    )
datatable(pcor_summary, caption = "Table 3: Completed EVAL & MLRA Summary with Spatial Changes")


pcor_sub2 <- subset(pcor_sub,
                    spatial_change == TRUE | pmu_seqnum == 2018
                    )

pcor_sub2$musym <- pcor_sub2$orig_musym
vars <- c("mlrassoarea", "projectname", "areasymbol", "new_musym", "new_nationalmusym")
nasis_qa1 <- {
  split(pcor_sub2, pcor_sub2[vars], drop = TRUE) ->.;
  lapply(., function(x) {
    data.frame(x[1, vars],
               n_musym = length(unique(x$musym)),
               musym_c = paste0(unique(x$musym), collapse=", "),
               nationalmusym_c = paste0(unique(x$nationalmusym), collapse=", ")
               )}) ->.;
  do.call("rbind", .)
  }
nasis_qa2 <- {
  split(pcor_sub2, pcor_sub2[vars], drop = TRUE) ->.;
  lapply(., function(x) {
    data.frame(x[1 , vars],
               musym         = unique(x$musym)
               )}) ->.;
  do.call("rbind", .)
  }
nasis_qa <- merge(nasis_qa2, nasis_qa1, 
                  by = vars, 
                  all = TRUE
                  )



# Geodatabase report (completed spatial changes in geodatabase)

idx <- names(mupolygon) %in% c("musym", "orig_musym", "editor_fie")
names(mupolygon)[which(idx)] <- c("new_musym", "musym", "editor")

mupolygon_edits <- subset(mupolygon, (musym != new_musym & musym != "") | !is.na(editor))

geo_qa1 <- mupolygon_edits %>%
  group_by(areasymbol, new_musym) %>%
  summarise(
    n_polygons = length(musym),
    acres = round(sum(shape_area*0.000247), 0),
    n_musym = length(unique(musym)),
    musym_c = paste0(unique(musym), collapse=", ")
    )

vars <- c("areasymbol", "new_musym")
geo_qa2 <- {
  split(mupolygon_edits, mupolygon_edits[, vars], drop = TRUE) ->.;
  lapply(., function(x) {
    data.frame(
      x[1, vars], 
      musym = unique(x$musym)
    )}) ->.; 
  do.call("rbind", .) ->.;
  row.names(.) <- 1:nrow(.)
  .->.;
  }

geo_qa <- left_join(geo_qa2, geo_qa1, by = c("areasymbol", "new_musym"))

# write.csv(geo_qa, 
#           paste0(
#             "C:/workspace2/report_spatial_geo_qa_", 
#             ssoffice, 
#             "_", 
#             format(Sys.time(), "%Y_%m_%d"), 
#             ".csv"), 
#           row.names = FALSE)
```

```{r, QA checks, echo=FALSE}

# QA checks

qa <- merge(nasis_qa, geo_qa, by = c("areasymbol", "musym", "new_musym"), all = TRUE) # match geo_qa2 to nasis_qa2

leg_key <- with(leg, paste0(areasymbol, "_", musym))
qa$qa_key  <- with(qa,  paste0(areasymbol, "_", new_musym))

qa <- transform(qa,
                in_project = !is.na(projectname),
                in_geodatabase = !is.na(n_polygons),
                in_legend = qa_key %in% leg_key # need to separate out this check, cuz
                )

qa_sub <- subset(qa, 
                 musym != new_musym #&
                 #substr(musym, 1, nchar(musym)) != new_musym &
                 #substr(musym, 2, nchar(musym) - 1) != new_musym
                 )

qa_project <- filter(qa_sub, in_project == FALSE)
qa_geo <- filter(qa_sub, in_geodatabase == FALSE)
qa_leg <- filter(qa, in_legend == FALSE)

if (dim(qa_project)[1] != 0) {
  datatable(qa_project, caption = "Table 4: Geodatabase changes missing from NASIS - Missing values (NA) need to be either added/removed from NASIS or the RTSD geodatabase, Otherwise they maybe splits that need to be relinked to a new additional mapunit.")
} else cat("SDJR Projects in NASIS match the Geodatabase")

if (dim(qa_geo)[1] != 0) {
  datatable(qa_geo, caption = "Table 5: NASIS changes missing from the Geodatabase - Missing values (NA) need to be either added/removed from NASIS or the RTSD geodatabase, Otherwise they maybe splits that need to be relinked to a new additional mapunit.")
} else cat("Geodatabase matches the SDJR Projects in NASIS")

if (dim(qa_leg)[1] != 0) {
  datatable(qa_leg, caption = "Table 6: Geodatabase musym missing from the legend")
  } else cat("Legends in NASIS match the Geodatabase")

# write.csv(qa, paste0("C:/workspace2/report_spatial_qa_", ssoffice, "_", format(Sys.time(), "%Y_%m_%d"), ".csv"))

# id <- match(nasis_qa2$key, geo_qa2$key, incomparables=TRUE)
# nasis_mis <- unique(nasis_qa2$key[is.na(id)]) # key present in NASIS, but missing from the geodatabase
# length(nasis_mis); print("number of musym missing from the RTSD geodatabase")

# id <- match(geo_qa2$key, nasis_qa2$key, incomparables=TRUE)
# geo_mis <- unique(geo_qa2$key[is.na(id)]) # key present in the geodatabase, but missing from NASIS
# length(geo_mis); print("number of musym missing from NASIS")

```

```{r, adjacent regions, echo=FALSE}
# Changes to adjacent regions
pcor_owners <- merge(qa, owners, by.x = "areasymbol", by.y = "AREASYMBOL", all.x = TRUE)

idx <- !(pcor_owners$Region %in% region)
vars <- c("Region", "mlrassoarea", "areasymbol", "projectname", "new_musym", "musym", "n_polygons", "acres", "in_legend")
outside <- pcor_owners[idx, vars]

if (dim(outside)[1] != 0) {
  datatable(outside, caption = "Table 7: MUSYM that need updating outside of Region")
  } else cat(c("No changes from", mlrassoarea, "to surrounding MLRA offices"))


# Need Check for changes from other regions


# Changes from adjacent offices
# For some reason this is catching a lot of spatial changes from adjacent Regions
idx <- pcor$mlrassoarea == ssoffice
pcor_in  <- pcor[idx, ]
pcor_out <- pcor[! idx, ]
pcor_out  <- merge(pcor_out, owners, by.x = "areasymbol", by.y = "AREASYMBOL", all.x = TRUE)

idx2 <- pcor_out$areasymbol %in% pcor_in$areasymbol & pcor_out$Region == 11 & ! pcor_out$projecttypename %in% c("MLRA", "SDJR") & (pcor_out$spatial_change == TRUE | is.na(pcor_out$spatial_change) | pcor_out$pmu_seqnum %in% fy) & grepl("11", pcor_out$mlrassoarea)
if (any(idx2 == TRUE)) {
 datatable(pcor_out[idx, ], caption = "Overlapping changes from adjacent offices")
 } else cat(c("No changes to", ssoffice, "from surround MLRA Offices")) 
```
