---
title: "SDJR and MLRA Summary"
author: "Stephen Roecker"
date: "December 12, 2016"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
options(stringsAsFactors = FALSE)

library(knitr)
library(RColorBrewer)
library(rgdal)
library(RCurl)
library(XML)
library(foreign)
library(reshape2)
library(plyr)
library(tidyverse)

source("C:/workspace2/github/soil-pit/trunk/queries/kssl_queries.R")
```


```{r load}
setwd("C:/Users/stephen.roecker/ownCloud/data/lims_data")

### Set parameters
ro <- 11
pt <- c("SDJR")
pt2 <- c("SDJR", "MLRA", "INITIAL", "ES")
pt3 <- c("SDJR", "MLRA")

data(state); st <- tolower(state.abb)
project_id <- "%25"

ssa <- read.dbf("M:/geodata/soils/soilsa_a_nrcs.dbf")
ownership <- read.csv("M:/geodata/soils/SSA_Regional_Ownership_MASTER_fy17.csv")

idx <- ownership$Region == 11
asymbol2 <- ownership[idx, "AREASYMBOL"]
asymbol <- paste0(unique(
  substr(asymbol2, 1, 2)), 
  "%25")


# fetch goals
years <- 2018
goals <- ldply(years, function(x){
  cat("fetching", x, "goal\n")
  goals_report(x, "%25")
  })


# reverse correlation
years <- 2017
start_date <- paste0("10/01/", years - 1)
finish_date <- paste0("09/30/", years)

rcors <- mapply(function(years, start_date, finish_date){
  cat("fetching", years, "reverse correlation\n")
  sdjr_correlation(asymbol, project_id, start_date, finish_date)
  }, years, start_date, finish_date, SIMPLIFY = FALSE); rcors <- do.call("rbind", rcors)


## Load data from files
goal_dates <- "2017_04_17"
corr_dates <- "2015_09_24"

goal_files <- paste0("lims_goals_fy", substr(2012:2017, 3, 4), "_", goal_dates, ".csv")
corr_files <- paste0("lims_correlation_fy", 2012:2015, "_", corr_dates, ".csv")

goals <- ldply(goal_files, read.csv)

rcors.. <- ldply(corr_files, read.csv)
rcors16 <- read.csv("lims_correlation_fy2016_AK%25_WY%25_2016_09_19.csv")
rcors17 <- read.csv("lims_correlation_fy2017_IA%25_WI%25_2017_04_17.csv")
rcors16 <- rbind(rcors16, rcors17[!names(rcors17) %in% c("pmu_seqnum", "state")])


## House Cleaning

### rcors
old_names <- c("sso", "old_musym", "old_natsym", "new_natsym", "old_mukey", "old_acres", "new_acres", "old_muname", "old_musym2", "spatial")
new_names <- c("office", "musym", "nationalmusym", "new_nationalmusym", "mukey", "muacres", "new_muacres", "muname", "musym_orig", "spatial_change")
names(rcors..) <- tolower(names(rcors..))
names(rcors..)[which(names(rcors..) %in% old_names)] <- new_names
rcors.. <- within(rcors.., {
                  projecttypename = substr(projectname, 1, 4)
                  state = substr(areasymbol, 1, 2)
                  })
rcors17 <- subset(rcors17, !is.na(new_mukey))
rcors17 <- within(rcors17, {
                  state = substr(areasymbol, 1, 2)
                  })

idx <- names(rcors..)[names(rcors..) %in% names(rcors16)]
rcors <- rbind(rcors..[idx], rcors16[idx])


### goals
old_names <- c("ssoffice", "projecttype")
new_names <- c("office", "projecttypename")
names(goals)[which(names(goals) %in% old_names)] <- new_names

### save copy
save(rcors, file = paste0("rcors_fy_summary_", corr_dates, "_", format(Sys.time(), "%Y_%m_%d.Rdata")))
save(goals, file = paste0("goals_fy_summary_", goal_dates, "_", format(Sys.time(), "%Y_%m_%d.Rdata")))
```


## Estimate Workload

```{r workload, eval=FALSE}

fte <- data.frame(
  fte = c(2, 2.5, 3, 2.5, 3, 5, 3, 5, 4, 1, 3),
  office = c("11-ATL", "11-AUR", "11-CLI", "11-FIN", "11-GAL", "11-IND", "11-JUE", "11-MAN", "11-SPR", "11-UNI", "11-WAV")
  ) # these numbers need to be updated to reflect retirements
wdays <- (52*5-10-3*5)*.75 # 52 weeks per year, 5 days per week, minus 10 holidays, minus 3 weeks vaction, at 75% an individuals time (i.e. minus 15% for TSS and 10% for miscellaneous)
# projects per person = 69 projects/ 3.5 fte
# days per project = workingdays/projects per person 

days_p_person <- function(days, projects, fte){
  days/(projects/fte)
}

goals_test <- mutate(goals,
                     mapunit = ifelse(projectname %in% c("^SDJR"), projectname, NA),
                     mapunit = sapply(projectname, function(x) unlist(strsplit(x, " - "))[3]),
                     components = sapply(mapunit, function(x) unlist(strsplit(x, " "))[1])
                     )

test <- goals_test %>%
  filter(region %in% ro) %>%
  group_by(fy = as.character(fy), office) %>%
  summarize(
    acres = sum(reported),
    n_projects = length(unique(projectname)),
    n_mapunits = length(unique(mapunit)),
    n_majors = length(unique(sapply(components, function(x) unlist(strsplit(x, "-"))[1])))
    ) %>% 
  inner_join(fte, by = "office")

test <- mutate(test,
               fte = round(fte, 1),
               days = round(fte*wdays, 0),
               days_project_fte = round(days / (n_projects / fte), 0), days_major_fte = round(days / (n_majors / fte), 0)
               ) %>%
  as.data.frame()
test2 <- rbind(test, c("2012:2016", "Average",
                       round(apply(test[3:9], 2, mean), 0))
               )

kable(test2)

# ggplot(test, aes(x = days_project_fte, y = acres, group = office)) +
#   geom_point() +
#   facet_wrap(fy ~ ., scales = "free_y")
```


## Examine Reported Acres

```{r goals, fig.height=8, fig.width=8}
temp <- goals %>%
  filter(region == ro & projecttypename %in% pt2) %>%
  group_by(fy, office, projecttypename) %>%
  summarize(
    n_projects = length(unique(projectname)),
    n_projects_completed = sum(goaled == reported),
    pct_n_completed = (n_projects_completed / n_projects) * 100,
    goaled = sum(goaled),
    reported = sum(reported)
    ) %>%
  as.data.frame()

temp <- mutate(temp,
               office = factor(office, levels = sort(unique(temp$office), decreasing = TRUE)),
               projecttypename = factor(projecttypename, levels = pt2)
               )

# Dotplot of Office vs Acres by Project Type
ggplot(temp, aes(x = reported, y = office)) + 
  geom_point() + 
  facet_grid(~ projecttypename ~ fy, scales = "free_x") +
  ggtitle("Dotplot of Acres Reported by Fiscal Year and Project Type")

# Scatterplot of n_projects vs n_projects_completed by Office and Project Type
# filter(temp, fy %in% 2012:2016) %>%
# ggplot(aes(x = n_projects, y = n_projects_completed, color = office)) +
#   geom_point(cex = 5) +
#   scale_colour_brewer(palette="RdYlBu") +
#   facet_grid(projecttypename ~ fy) +
#   coord_fixed()
#   ggtitle("Scatterplot of Projects Reported by Fiscal Year and Project Type")

filter(temp, fy == 2017) %>%
ggplot(aes(x = pct_n_completed, y = n_projects, color = office)) +
  geom_point(cex = 5) +
  scale_colour_brewer(palette="RdYlBu") +
  xlim(0, 100) +
  facet_grid(projecttypename ~ fy, scales = "free_y") +
  coord_fixed()
  ggtitle("Scatterplot of Projects Reported by Fiscal Year and Project Type")

# Time Series of Acres Reported by Office and Project Type
ggplot(temp, aes(x = fy, y = reported, group = office, linetype = office, shape = office)) + 
  geom_line(size = 0.7) + 
  geom_point(size = 2.5) +
  scale_shape_manual(values=1:nlevels(temp$office)) +
  facet_grid(projecttypename ~ ., scales = "free_y")
  ggtitle("Time Series of Acres Reported by Fiscal Year and Project Type")

# Time Series of n_projects_completed Reported by Office and Project Type
ggplot(temp, aes(x = fy, y = n_projects_completed, group = office, linetype = office, shape = office)) + 
  geom_line(size = 0.7) + 
  geom_point(size = 2.5) +
  scale_shape_manual(values=1:nlevels(temp$office)) +
  facet_grid(projecttypename ~ ., scales = "free_y") +
  ggtitle("Time Series of n_projects_completed Reported by Fiscal Year and Project Type")

temp <- filter(temp, projecttypename %in% pt3)
rank_acres <- group_by(temp, office) %>%
  summarize(acres = sum(reported)) %>%
  arrange(- acres) %>%
  mutate(acres = formatC(acres, format = "E", digits = 1)) %>%
  t() %>% as.data.frame()
rank_projects <- group_by(temp, office) %>%
  summarize(projects = sum(n_projects_completed)) %>%
  arrange(- projects) %>%
  t() %>% as.data.frame()
kable(rank_acres)
kable(rank_projects)
```


## Compare Project Acres to Goaled Acres

```{r compare}

rcors_acres <- rcors %>% 
  filter(region == ro & projecttypename %in% pt) %>%
  group_by(fy, region, office, projectname, projectiid, areasymbol) %>%
  summarize(
    n = length(unique(musym_orig)), 
    old_acres = sum(unique(muacres)), 
    new_acres = sum(unique(new_muacres))
    ) %>%
  group_by(fy, region, office, projectname) %>% 
  summarize(
    n = sum(n),
    old_acres = sum(old_acres),
    new_acres = sum(new_acres)
    )

temp <- left_join(goals, rcors_acres, by = "projectname")

progress <- temp %>%
  filter(region.x == ro & projecttypename %in% pt) %>%
  group_by(region.x, fy.x, projecttypename) %>% 
  summarize(reported = sum(reported) / 0.2,
            new_acres = sum(new_acres, na.rm = TRUE),
            dif_acres = sum(reported - new_acres, na.rm = TRUE),
            dif_pct = 100 - round(reported / new_acres * 100)
            ) 

kable(progress)
```


## Summarize Spatial Changes

```{r spatial}
r11_spatial <- rcors %>%
  filter(region %in% ro & spatial_change == TRUE & projecttypename %in% pt3) %>%
  group_by(fy, projecttypename, region, office) %>% 
    summarize(
      acres = sum(muacres, na.rm = TRUE),
      n_areasymbol = length(unique(areasymbol)),
      n_musym = length(unique(musym_orig))
      ) %>%
  arrange(desc(acres)) %>%
  as.data.frame()

filter(r11_spatial, fy == 2017) %>%
ggplot(aes(x = n_musym, y = n_areasymbol, group = fy, color = office)) + 
  geom_point(cex = 5) + 
  scale_colour_brewer(palette="RdYlBu") +
  facet_grid(projecttypename ~ fy, scales = "free_y")
```


## Map Progress by AREASYMBOL

```{r map_as, fig.height=10, fig.width=8}
rcors_as <- rcors %>%
  filter(region == ro & projecttypename %in% pt & substr(areasymbol, 1, 2) == "IL") %>%
  group_by(fy, region, projectiid, projecttypename, areasymbol) %>%
  summarize(
    n = length(unique(new_mukey)), 
    muacres = sum(unique(muacres)), 
    new_muacres = sum(unique(new_muacres))
  ) %>%
  group_by(fy, region, areasymbol) %>%
  summarize(
    muacres = sum(muacres),
    new_muacres = sum(new_muacres)
  ) %>%
  as.data.frame()

rcors_as$acres <- cut(rcors_as$new_muacres, 
                      breaks = c(0, 10000, 50000, 100000, 150000, 200000), 
                      labels = c("0 - 10,000", "10,000 - 50,000", "50,000 - 100,000", "100,000 - 150,000", "150,000 - 200,000")
                      )

rcors_as_w <- select(rcors_as, fy, region, areasymbol, acres) %>% 
  spread(fy, acres) # spread recycles non-grouping variables, so it needs to be combined with select, reshape() silently drops them but gives a warning if they vary
rcors_as_w1 <- reshape(rcors_as, idvar = "areasymbol", v.names = "acres", timevar = "fy", direction = "wide")
# rcors_as_w2 <- dcast(rcors_as, region + areasymbol ~ fy, value.var = "acres") # converts acres to characters instead of factors

fy <- paste0(sort(unique(rcors_as$fy)))
FY <- paste0("FY", sort(unique(rcors_as$fy)))
names(rcors_as_w)[which(names(rcors_as_w) %in% fy)] <- FY

ssa3 <- merge(ssa_sf, rcors_as_w, by = "areasymbol", all.x = TRUE)
temp_sub1 <- subset(ssa3, region == ro, select = FY)

# Use the following code to plot all the county boundaries for states that intersect Region 11
bb <- st_bbox(temp_sub1)
ssa3$state <- substr(ssa_sf$areasymbol, 1, 2)
st <- toupper(c("il"))
temp_sub2 <- filter(ssa3, state %in% st) %>% select(FY2013, FY2014, FY2015, FY2016, FY2017))

spplot(temp_sub2,
       main = paste0("Time Series of Updated ", paste0(pt, collapse = " & "), " Acres by County"),
       xlim = bb[1, ], ylim = bb[2, ],
       as.table = TRUE, layout = c(2, 2),
       col.regions = brewer.pal(5, "YlOrRd"),
       colorkey = list(space = "bottom", height = 1)
       )
```


## Summarize and plot acres by musym

```{r map_musym, eval=FALSE, echo=FALSE}
corrs_mukey <- ddply(corrs, .(fy, region), summarize, MUKEY = unique(new_mukey))
corrs_ssaMusym <- ddply(corrs, .(fy, region), summarize, MUKEY = unique(paste0(areasymbol,"_", old_musym)))

fy12 <- subset(corrs_mukey, fy == 2012 & region == 11)
fy13 <- subset(corrs_ssaMusym, fy == 2013 & region == 11); 
fy14 <- subset(corrs_mukey, fy == 2014 & region == 11)
fy15 <- subset(corrs_mukey, fy == 2015 & region == 11)

fy13_r <- raster("M:/geodata/soils/gssurgo_fy13_250m.tif")
fy13_r_dbf <- read.dbf("M:/geodata/soils/gssurgo_fy13_30m.tif.vat.dbf")
fy13_r <- ratify(fy13_r, count=TRUE)
rat <- levels(fy13_r)[[1]]
names(fy13_r_dbf)[1] <- "ID"
names(fy13_r_dbf)[3] <- "MUKEY"
rat_new <- join(rat, fy13_r_dbf, type = "left", by = "ID")
rat_new <- join(rat_new, fy13, type = "left", by = "MUKEY")
fy13_r_2 <- fy13_r
levels(fy13_r_2) <- rat_new
# fy13_r_new <- deratify(fy13_r_2, att='fy', filename='gSSURGO_fy13_progress.tif', overwrite=TRUE, datatype='INT4U', format='GTiff', progress = "text")


fy14_r <- raster("M:/geodata/soils/gssurgo_fy14_250m.tif")
fy14_r_dbf <- read.dbf("M:/geodata/soils/gssurgo_fy14_30m.tif.vat.dbf")
fy14_r <- ratify(fy14_r, count=TRUE)
rat <- levels(fy14_r)[[1]]
names(fy14_r_dbf)[1] <- "ID"
rat_new <- join(rat, fy14_r_dbf, type = "left", by = "ID")
rat_new <- join(rat_new, fy14, type = "left", by = "MUKEY")
fy14_r_2 <- fy14_r
levels(fy14_r_2) <- rat_new
# fy14_r_new <- deratify(fy14_r_2, att='fy', filename='gSSURGO_fy14_progress.tif', overwrite=TRUE, datatype='INT4U', format='GTiff', progress = "text")


fy15_r <- raster("M:/geodata/soils/gssurgo_fy15_250m.tif")
fy15_r_dbf <- read.dbf("M:/geodata/soils/gssurgo_fy15_30m.tif.vat.dbf")
fy15_r <- ratify(fy15_r, count=TRUE)
rat <- levels(fy15_r)[[1]]
names(fy15_r_dbf)[1] <- "ID"
rat_new <- join(rat, fy15_r_dbf, type = "left", by = "ID")
rat_new <- join(rat_new, fy15, type = "left", by = "MUKEY")
levels(fy15_r) <- rat_new
# fy15_r_new <- deratify(fy15_r, att='fy', filename='gSSURGO_fy15_progress.tif', overwrite=TRUE, datatype='INT4U', format='GTiff', progress = "text")

fy13_r_new <- raster("C:/workspace/gSSURGO_fy13_progress.tif")
fy14_r_new <- raster("C:/workspace/gSSURGO_fy14_progress.tif")
fy15_r_new <- raster("C:/workspace/gSSURGO_fy15_progress.tif")
ssa <- readOGR(dsn = "M:/geodata/soils/soilsa_a_nrcs.shp", layer = "soilsa_a_nrcs", encoding = "ESRI Shapefile")
ssa <- spTransform(ssa, CRS("+init=epsg:5070"))
ssa$state <- substr(ssa$areasymbol, 1, 2)
wi <- subset(ssa, state == "WI")
test <- stack(fy13_r_new, fy14_r_new, fy15_r_new)
names(test) <- c("FY13_SDJR_Progress", "FY14_SDJR_Progress", "FY15_SDJR_Progress")
spplot(test, sp.layout = wi, maxpixels = 5000000, xlim = bbox(wi)[1, ], ylim = bbox(wi)[2, ], colorkey = FALSE, col.regions = "blue", strip = strip.custom(bg = grey(0.85)))

test_f <- function(x) test = unique(x)

test <- by(corrs, corrs[c("fy", "region")], function(x) cbind(unique(x$new_mukey), unique(x$old_mukey)))
test2 <- cbind(expand.grid(dimnames(test)), do.call(rbind, test))
```
