# These figures don't compare with Alena's spreadsheets. Her spreadsheets have additional counties that aren't captured in the Project Record.

setwd("I:/")

library(plyr)

# Summarize the NASIS web report "Identify surveys with projects ready to upload" for State Soil Scientists

ssurgo.v <- c("ia.csv", "il.csv", "ks.csv", "in.csv", "mi.csv", "mn.csv", "mo.csv", "ne.csv", "oh.csv", "ok.csv", "sd.csv", "wi.csv")

combine.df <- function(ssurgo.v){
  l <- list()
  l.s <- list()
  l.l <- list()  
  for(i in seq(ssurgo.v)){
   l[[i]] <- read.csv(ssurgo.v[i])
   l.s[[i]] <- subset(l[[i]], State.Responsible == "Indiana")
   l.l[[i]] <- length(unique(l.s[[i]]$Area.Symbol))   
  }
  df <- ldply(l.s)
  v <- unlist(l.l)
  return(list(df=df, v=v))
}

nasis <- combine.df(ssurgo.v)
nasis.df <- nasis$df

length(unique(nasis.df$Project.Name)) # number of sdjr projects
length(unique(nasis.df$Area.Symbol)) # number of ssa

# Summarize DU report vs. Project_Record
# Using the select by location function in ArcGIS I get a total of 99 counties need spatial recert, from the RTSD-SAPOLYGON, while 136 for the Region SSURGO
# du.pr.m dataframe shows overlap between the DU report and Project Record Feature Class.
# The DU report say 83 counties need to be updated, but the Project Record ID says 73.
# When comparing the Project Record and SAPOLYGON for the Region I get 65 counties need spatial cert and an additional 8 need update outside our region

# DU report
du <- read.csv("du.csv", stringsAsFactors = FALSE) # du report
du.r11 <- subset(du, State.Responsible == "Indiana" & Office == "11-ATL") # subset for Region 11

ddply(du.r11, .(Office), summarize, length(Project.Name)); # number of projects per office; print(du.r11.n)
ddply(du.r11, .(Project.Name), summarize, length(Project.Name)); # number of musym per project
ddply(du.r11, .(Area.Symbol), summarize, length(Project.Name)); # number of musym per ssa

du.r11.df <- ddply(du.r11, .(Office, Area.Symbol, pname = abbreviate(Project.Name, 30)), summarize, musym = paste0(c(unique(musym)), collapse=", ")); # number of musym per project

du.check <- ddply(du.r11, .(Office, Area.Symbol), summarize, musym = unique(musym))
du.check$key <- paste(du.check$Area.Symbol, du.check$musym, sep=":")
du.musym <- sort(unique(du.r11$musym))

```{r, summarize geodatabase tabular changes}
# This assumes no changes have been made to the ORIG columns, could run a check against an unedited copy. Need to add addition scripts to see if the number of MUSYM edited = the total number of MUSYM.

library(plyr)

mupolygon <- read.csv("mupolygon.csv", stringsAsFactors=FALSE)
id <- mupolygon$Editor_Field != ""
edit <- mupolygon[id, ]

# Summarize tabular changes
id <- edit$MUSYM != edit$ORIG_MUSYM
tab <- edit[id, ]


geotab <- ddply(tab, .(AREASYMBOL), summarize, Check = all(ORIG_MUKEY = MUKEY), nPolygons = length(ORIG_MUKEY), ORIG_MUSYM = paste(c(unique(ORIG_MUSYM)), collapse=", "),  MUSYM = paste(c(unique(MUSYM)), collapse=", "), Acres = round(sum(Shape_Area*0.000247), 0))

geo.check <- ddply(tab, .(AREASYMBOL), summarize, ORIG_MUSYM = unique(ORIG_MUSYM))
geo.check$key <- paste(geo.check$AREASYMBOL, geo.check$ORIG_MUSYM, sep=":")
geo.musym <- sort(unique(tab$ORIG_MUSYM))
  
# DU report against mupolygon
check1 <- join(geo.check, du.check, by="key", match="first") # SSA:MUSYM match
print(check1[, -1]) # matches between du and geo

# non-matches between du and geo
# 11-ATL has 8 missing musym from geo
all(du.musym %in% geo.musym)
sum(sum(du.musym %in% geo.musym))
id <- match(du.musym, geo.musym, incomparables=TRUE)
du.musym[is.na(id)]
```


# Project Record
pr <- read.csv("Region_11_Project_Record_09092014.txt")
pr.c <- subset(pr, RECERT_NEEDED == "Yes")
length(unique(pr.c$PROJECT_NAME)); # number of projects
length(unique(pr.c$AREASYMBOL)); # number of ssa
pr.c.n <- ddply(pr.c, .(PROJECT_NAME, RECERT_NEEDED), summarize, length(PROJECT_NAME)); # number of polygons per project
pr.c.n2 <- ddply(pr.c, .(AREASYMBOL, RECERT_NEEDED), summarize, length(PROJECT_NAME)); # number of polygons per area
names(pr.c.n2) <- c("AREASYMBOL", "RECERT_NEEDED", "nMUSYM")


# Compare DU Report vs Project Record by SDJR projects
du.pr.m <- merge(pr.c.n, du.r11.n, by.x="PROJECT_NAME", by.y="Project.Name",  all=T)
names(du.pr.m) <- c("Project.Name", "Recert.Needed", "npolyons", "nMUSYM")
write.csv(du.pr.m, "Region11_DUcert.csv")

# compare RTSD-SAPOLYGON vs
sa <- read.csv("SAPOLYGON.txt")
sa.n <- ddply(sa, .(AREASYMBOL), summarize, length(AREASYMBOL)); # number of polygons per ssa
names(sa.n) <- c("AREASYMBOL", "nSSA")
sa.pr.m <- merge(sa.n, pr.c.n2, by="AREASYMBOL") # number of musym per ssa that need recert
length(unique(sa.pr.m$AREASYMBOL)) # number of ssa within Region 11 needing recert 
sa.pr.m2 <- merge(subset(sa.pr.m, select=c("AREASYMBOL", "nMUSYM")), pr.c.n2, by="AREASYMBOL", all=T) # number of musym per ssa that need recert, 65 ssa in Region 11 need recert and 8 in other regions
write.csv(sa.pr.m2, "Region11_SAcert.csv")