# Pedon report

```{r}
# Set Global Parameters
series <- "Lecyr"
p <- c(0, 0.10, 0.5, 0.90, 1)
```

```{r LoadPackages, include=FALSE}
# load libraries
library(aqp)
library(soilDB)
library(reshape)
library(plyr)
library(lattice)
library(xtable)
```

```{r, load-data, echo=FALSE}
# source custom R functions


# load NASIS data
f <- fetchNASIS()
f <- subsetProfiles(f, s="taxonname == series")
f@horizons$hzname[is.na(f@horizons$hzname)] <- "NA"
names(f@horizons)[15] <- "fragvoltot"
f@horizons$d_chroma <- as.numeric("NA")
f@horizons$m_chroma <- as.numeric("NA")

# Function
conditional.l.rv.h.summary <- function(x) {
  variable <- unique(x$variable)
  v <- na.omit(x$value) # extract column, from long-formatted input data
  precision <- if(variable == 'phfield') 1 else 0
  ci <- quantile(v, na.rm=TRUE, probs=p) 
  d <- data.frame(min=ci[1], low=ci[2], rv=ci[3], high=ci[4], max=ci[5], stringsAsFactors=FALSE) # combine into DF
  d$range <- with(d, paste("(", paste(round(c(min, low, rv, high, max), precision), collapse=', '), ")", sep="")) # add 'range' column for pretty-printing
  return(d[6])
  }
```

## Summary of Sites
```{r, echo=FALSE}
# Site information
s <- site(f)
subset(s, select=c("pedon_id", "taxonname", "pedon_type", "describer"))

# Summarize surface rock fragments
s$total_srf <- s$surface_gravel+s$surface_cobbles+s$surface_stones+s$surface_boulders+s$surface_flagstones+s$surface_channers
s$gravel <- s$surface_fgravel-s$surface_gravel
s.m <- melt(s, measure.vars=c("total_srf", "surface_fgravel", "surface_gravel", "surface_cobbles", "surface_stones", "surface_boulders", "surface_channers", "surface_flagstones"))
s.summary <- ddply(s.m, .(variable), .fun=conditional.l.rv.h.summary)

# Box plots of surface rock fragments
bwplot(variable~value, data=s.m, scales=list(x="free"), xlab="percent")          

# Range in characteristics of surface rock fragments (min, 10th, median, 90th, max)
format(cast(s.summary, ~variable, value='range'), justify="centre")
```

## Summary of Pedons
```{r, echo=FALSE, results='asis', options("xtable.type" = "html")}
plot(f, label="pedon_id")

h <- horizons(f)

# Horizon designations by generic horizon
if(length(na.exclude(f@horizons$genhz))>0){
print(xtable(addmargins(table(f@horizons$hzname, f@horizons$hzname))))
}

# Summarize numeric variables by generic horizon
h$gravel <- h$gravel-h$fine_gravel

hp.m <- melt(h, id.vars="hzname", measure.vars=c('clay', 'sand', 'fine_gravel', 'gravel', 'cobbles', 'stones', 'fragvoltot'))
hp.cs <- ddply(hp.m, .(variable, hzname), .fun=conditional.l.rv.h.summary)

hc.m <- melt(h, id.vars="hzname", measure.vars=c('phfield', 'd_value', 'd_chroma', 'm_value', 'm_chroma'))
hc.cs <- ddply(hc.m, .(variable, hzname), .fun=conditional.l.rv.h.summary)

thk <- ddply(h, .(peiid, hzname), summarize, thickness=sum(hzdepb-hzdept))
thk.m <- melt(thk, id.vars="hzname", measure.vars="thickness")
thk.cs <- ddply(thk.m, .(variable, hzname), .fun=conditional.l.rv.h.summary)

data.n <- ddply(h, .(hzname), .drop=T, summarize, n=as.character(length(hzname)))

# Range in characteristics for generic horizons (min, 10th, median, 90th, max)
hp.c <- cast(hp.cs, hzname ~ variable, value='range')
hp.cm <- merge(hp.c, data.n, by="hzname")
print.xtable(hp.cm)

# Box plots of numeric variables by generic horizon
bwplot(hzname ~ value|variable, data=rbind(hp.m, thk.m), scales=list(x="free"))          

# Texture by generic horizon
print(xtable(addmargins(table(h$hzname, h$texture_class, exclude=NULL))))

# Tex Mod & Class by generic horizon
addmargins(table(h$hzname, h$texture, exclude=NULL))

# Dry hue by generic horizon
addmargins(table(h$hzname, h$d_hue, exclude=NULL))
      
# Moist hue by generic horizon
addmargins(table(h$hzname, h$m_hue, exclude=NULL))
      
# Dry value by generic horizon
addmargins(table(h$hzname, h$d_value, exclude=NULL))

# Moist value by generic horizon
addmargins(table(h$hzname, h$m_value, exclude=NULL))

# Dry chroma by generic horizon
addmargins(table(h$hzname, h$d_chroma, exclude=NULL))

# Moist chroma by generic horizon
addmargins(table(h$hzname, h$m_chroma, exclude=NULL))

# Effervescence by generic horizon
addmargins(table(h$hzname, h$effervescence, exclude=NULL))

# Thickness of diagnostic horizons
diag.thk <- ddply(f@diagnostic, .(peiid, diag_kind), summarize, thickness=sum(featdepb-featdept))
diag.m <- melt(f@diagnostic, id.vars="diag_kind", measure.vars=c('featdept', 'featdepb'))
diag.thk.m <- melt(diag.thk, id.vars="diag_kind", measure.vars='thickness')
diag.m <- rbind(diag.m, diag.thk.m)
d.cs <- ddply(diag.m, .(variable, diag_kind), .fun=conditional.l.rv.h.summary)
format(cast(d.cs, diag_kind ~ variable, value='range'), justify="centre")

bwplot(diag_kind ~ value|variable, data=diag.m, scales=list(x="free"), xlab="cm")          
```

