---
title: "DSP POX-C Supplement"
author: "Wills et al"
date: "March 12, 2018"
output: html_document
---

```{r setup, include=FALSE}

#rm(list=ls()) #clear previous data

require("knitr")
knitr::opts_chunk$set(echo = TRUE, comment = "#", warning = FALSE, message = FALSE, error =FALSE, tidy.opts=list(width.cutoff=60),tidy=TRUE)

#checks for packages and downloads as necessary
list.of.packages <- c("tidyverse", "ggthemes", "RCurl", "gridExtra", "GGally", "clhs", "ggbeeswarm", "ggridges" ,"ggjoy", "viridis", "readxl")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

library(tidyverse)
library(RCurl)
library(gridExtra)
library(GGally)
library(clhs)
library(ggjoy)
library(ggbeeswarm)
library(ggridges)
library(viridis)
library(readxl)

```

##DSP Projects POX_C Analysis

###DSP POXC values

```{r dsp_data}
#load data from DSP projects


#POX (AC) sample pool used to select samples for further analysis
DSP_url <- 'https://nrcs.box.com/shared/static/8s7lyc7py48ehxafshblio4adh8mb4by.xlsx'
ifelse(!file.exists('DSP_project_master.xlsx'), download.file(DSP_url, destfile = 'DSP_project_master.xlsx'), "File already downloaded")


dsp <- read_excel("DSP_project_master.xlsx", sheet ="All Data Assembled" )
label <- read_excel("DSP_project_master.xlsx", sheet ="dsp_coredata_label")
site <- read_excel("DSP_project_master.xlsx", sheet ="DSP_site")


dsp <- read_excel("DSP_project_master.xlsx", 
     sheet = "All Data Assembled", col_types = c("text", 
         "text", "text", "numeric", "text", "text", "text", "numeric", "text", "text", "text", "text", "text", "text", 
         "text", "text", "text", "text", "text", "text", "numeric", "text", "numeric", "text", "numeric", "numeric", 
         "numeric", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", 
         "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",  "numeric", "numeric", "numeric", "numeric",
         "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
         "numeric",  "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", 
         "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",  "numeric",
         "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
         "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))



#you may want to select for specific DSP Project - Name == "???" here

names(dsp[grep('BD', names(dsp))])


#table of record counts by BD method
kable(dsp %>%
  select(Name, contains("BD")) %>%
  group_by(Name) %>%
  summarise_all(funs(sum(!is.na(.)))))

#DATA prep
#Order of bulk density selection - change order if desired
bd_1 <- "BD_core_fld"
bd_2 <- "BD_fieldcore"
bd_3 <- "BD_clod_13"
bd_4 <- "BD_compcav"
bd_5 <- "BD_recon13"

#create new data element that combines all bulk density methods'

dsp <- dsp %>%
  mutate(BulkDensity = if_else(!is.na(!!as.name(bd_1)), !!as.name(bd_1),
         ifelse(!is.na(!!as.name(bd_2)), !!as.name(bd_2), 
                ifelse(!is.na(!!as.name(bd_3)), !!as.name(bd_3),
                       ifelse(!is.na(!!as.name(bd_4)), !!as.name(bd_4),
                              !!as.name(bd_5))
                              )))
         )


dsp <-  dsp %>%
    mutate(bd_source = ifelse(!is.na(dsp[,bd_1]), bd_1, 
                         ifelse(!is.na(dsp[,bd_2]), bd_2,
                                ifelse(!is.na(dsp[,bd_3]), bd_3,
                                       ifelse(!is.na(dsp[,bd_4]), bd_4,
                                              bd_5))))
    )



summary(dsp$bd_source)
table(dsp$Name, dsp$bd_source)


# calculate SOC - soil organic carbon
SOC_calc <- dsp$Tot_C - 0.11*dsp$CaCarb


dsp$SOC <- as.numeric(
  ifelse(!is.na(dsp$Est_OC) & dsp$Est_OC>=0, dsp$Est_OC,   
         ifelse(!is.na(dsp$Tot_C), dsp$Tot_C,                       
                ifelse(!is.na(dsp$Total.C), dsp$Total.C, 
                       NA ))))

summary(dsp$SOC)



#set values less than zero to zero
dsp$SOC[dsp$SOC<0]<- 0

summary(dsp$SOC)

dsp$TN <- as.numeric(ifelse(!is.na(dsp$Tot_N), dsp$Tot_N, dsp$Total.N))  

summary(dsp$TN)


#limit the dataset to columns we're intersted in
dsp <- dsp %>%
  select(Name, DSP.Project, UserPedonID, labsampno, dsp_limslayer_ID, Soil, Comparison, COND, PlotID, hor_desg, Hor_sequ, Comp_layer, hor_top, hor_bot, AggStab, Bgluc, Pom_C, Pom_N, Pom_S, POX_C, Tot_C, Tot_N, Tot_S, CaCarb ,ph_h20, Clay, BulkDensity, SOC, TN)



hist(dsp$POX_C)
hist(dsp$Bgluc)
hist(dsp$Pom_C)
hist(dsp$AggStab)
     

hist(log(dsp$POX_C))
hist(log(dsp$Bgluc))
hist(log(dsp$Pom_C))
hist(log(dsp$AggStab))

POX <- log(dsp$POX_C)
Bgluc <- log(dsp$Bgluc)
POMC <- log(dsp$Pom_C)
SOC <- log(dsp$SOC)
AggStab <- log10(dsp$AggStab)

#Transform distibutions
#function that returns values <1

signedlog10 = function(x) {
 ifelse(abs(x) <= 1, 0, sign(x)*log10(abs(x)))
}

signedlog = function(x) {
  ifelse(abs(x) <= 1, 0, sign(x)*log(abs(x)))
}

#need to revisit
dsp$logOC <- log(dsp$SOC)
dsp$logPOX <- signedlog10(dsp$POX_C)
dsp$logBgluc <- log10(as.numeric(dsp$Bgluc))
dsp$logPOMC <- log10(dsp$Pom_C)
dsp$logAggStab <- signedlog(dsp$AggStab)


```

Explore POXC values throughout the samples

```{r explore}

#assign master horizons for subsetting

dsp <- dsp  %>%
  mutate(Master = case_when(
     grepl("O+", hor_desg) ~ "O",
    grepl("E+", hor_desg) ~ "E",
     grepl("A+", hor_desg) ~ "A",
    grepl("B+", hor_desg) ~ "B",
    grepl("C+", hor_desg) ~ "C"))

 table(as.factor(dsp$hor_desg), as.factor(dsp$Master))

dsp %>% ggplot(aes(x=POX_C, y = hor_top)) + geom_point(aes(color = Master))

dsp %>% ggplot(aes(x=POX_C, y = Tot_C)) + geom_point(aes(color = Master))
dsp %>% ggplot(aes(x=POX_C, y = SOC)) + geom_point(aes(color = Master))


dsp %>% filter(Hor_sequ ==1) %>% ggplot(aes(x = POX_C)) + geom_density(aes(fill = Master))


dsp %>% 
  ggplot(aes(x = POX_C, y = Master, fill = COND)) + 
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.5)

dsp %>% 
  ggplot(aes(x = POX_C, y = Master, fill = Soil)) + 
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.5)


dsp %>% 
  ggplot(aes(x = POX_C, fill = Master, y = Soil)) + 
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.5)


#very high values are all associated with a particular organic soil project; remove those
dsp %>% filter(Name != "MI_org") %>% ggplot(aes(x = POX_C)) + geom_density(aes(fill = Master))

#much higher values for O horizons
dsp %>% filter(Master != "O", !is.na(Master)) %>% ggplot(aes(x = POX_C)) + geom_density(aes(fill = Master))
dsp %>% filter(Master != "O", !is.na(Master)) %>% ggplot(aes(x=POX_C, y = SOC)) + geom_point(aes(color = Master))

dsp %>% filter(Master != "O", !is.na(Master)) %>% ggplot(aes(x=POX_C, y = SOC)) + geom_point(aes(color = COND)) + facet_wrap(~Master)

dsp %>% filter(Master == "A", !is.na(Master)) %>% ggplot(aes(x=POX_C, y = SOC)) + geom_point(aes(color = COND)) 

dsp %>% filter(Master == "A", !is.na(Master)) %>% ggplot(aes(x=POX_C, y = SOC, color = Soil)) + geom_point(aes(color = Soil)) + geom_smooth()


dsp %>% filter(Hor_sequ ==1, Name != "MI_org", Master != "O") %>% ggplot(aes(x = POX_C)) + geom_density(aes(fill = Master))

dsp %>% filter(Hor_sequ ==1, Name != "MI_org", Master != "O") %>% ggplot(aes(x = logPOX)) + geom_density(aes(fill = Master))


Master != "O"



dsp %>% filter(Hor_sequ ==1, Name != "MI_org")
  ggplot(aes(x = Tot_C, y = Name, fill = COND)) + 
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.5)

  
dsp %>% 
  ggplot(aes(x = Tot_C, y = Master, fill = COND)) + 
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.5)  
  
#all data
dsp%>%
  ggplot(aes(x=Tot_C, y = Name, fill = factor(..quantile..))) +
  stat_density_ridges(geom="density_ridges_gradient", calc_ecdf = TRUE, quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis(discrete = TRUE, name = "Quartiles") 
```


Evaluate surface and make comparisons

```{r surf_POXC}


dsp %>% filter(Hor_sequ ==1, Name != "MI_org") %>% ggplot(aes(x = POX_C)) + geom_density()

dsp %>% filter(Hor_sequ ==1, Name != "MI_org") %>% ggplot(aes(x = logPOX)) + geom_density()


#very high values are all associated with a particular organic soil project; remove those
#look only at surface horizons

surf <- dsp %>% filter(Hor_sequ ==1, Name != "MI_org") %>%
  mutate(Master = case_when(
     grepl("O", hor_desg) ~ "O",
    grepl("A", hor_desg) ~ "A",
    grepl("B", hor_desg) ~ "B",
    grepl("C", hor_desg) ~ "C"))


surf %>%
  ggplot(aes(x = Tot_C, y = Name, fill = COND)) + 
  stat_density_ridges(quantile_lines = TRUE, quantiles = 2, alpha = 0.5)


surf %>%
  ggplot(aes(x=Tot_C, y = Name, fill = factor(..quantile..))) +
  stat_density_ridges(geom="density_ridges_gradient", calc_ecdf = TRUE, quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis(discrete = TRUE, name = "Quartiles") 

surf %>%
  ggplot(aes(x=POX_C, y = Name, fill = factor(..quantile..))) +
  stat_density_ridges(geom="density_ridges_gradient", calc_ecdf = TRUE, quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis(discrete = TRUE, name = "Quartiles") +theme_ridges()


surf %>% filter( Name =="SD_multi") %>%
  ggplot(aes(x=Tot_C, y = Soil, fill = factor(..quantile..))) +
  stat_density_ridges(geom="density_ridges_gradient", calc_ecdf = TRUE, quantiles = 4, quantile_lines = TRUE) +
  scale_fill_viridis(discrete = TRUE, name = "Quartiles") + theme_ridges()

surf %>% filter( Name =="SD_multi") %>%
  ggplot(aes(x=POX_C, y = Soil, fill = COND)) +
  stat_density_ridges(calc_ecdf = TRUE, quantiles = 4, quantile_lines = TRUE) + theme_ridges() +
    geom_density_ridges(aes(point_color = COND, point_fill = COND, point_shape = COND), alpha = 0.2, jittered_points = TRUE)

surf %>% filter( Name =="SD_multi") %>%
  ggplot(aes(x=POX_C, y = `KSSL Project` , fill = COND)) +
  stat_density_ridges(calc_ecdf = TRUE, quantiles = 4, quantile_lines = TRUE) + theme_ridges() +
    geom_density_ridges(aes(point_color = COND, point_fill = COND, point_shape = COND), alpha = 0.2, jittered_points = TRUE)



surf %>% filter( Name =="SD_multi") %>%  mutate(COND = as.factor(COND)) %>%
  ggplot(aes(x=POX_C, y = Soil, fill = COND)) +
  geom_density_ridges(aes(point_color = COND, point_fill = COND, point_shape = COND), alpha = 0.2, jittered_points = TRUE) + theme_ridges()

ggcorr(surf %>% select(SOC, POX_C, ph_h20, Clay, Bgluc, BulkDensity))

  


```
