---
title: "Denham Data Logger"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(maps) #create maps
library(plyr) #splitting, applying, & combining data
library(ggplot2) #plot
library(lattice) #xy plot

```

## R Markdown

#Project Area Location


```{r final project, echo=FALSE}

map('county', 'indiana') # plot county boundaries for all of Indiana
map('county', 'indiana,pulaski', add=T, fill = T, col="purple") #add Pulaski County, Indiana in purple to map
map.text("county", "indiana,Pulaski", add=T) #add text for Pulaski

#read all the csv files from a folder as one table
denham=ldply(list.files(path="E:/geodata/project_data/11IND//IPO_Data_Loggers/data_loggers_2017/denham_Pulaski_IN",pattern="csv",full.names=TRUE),function(filename) {
  dum=read.csv(filename)
  dum$filename=filename
  return(dum)
})

#read the date from the table
denham$date <- as.Date (denham$date, '%m/%d/%Y')

#plot feet line -data from the csv before conversion to centimeters - shows data prior to 2008 is scewed
ggplot(data=denham, aes (date, feet)) +geom_line(colour='purple')+ ylim(5, -2.5)+ggtitle("Feet Years")+theme(plot.title = element_text(lineheight=.8, face="bold")) 

```

 

**Plots:**

```{r pressure, echo=FALSE}
denham$year <- as.Date(cut(denham$date,
                              breaks = "year"))
denham$month <- as.Date(cut(denham$date,
                              breaks = "month"))
denham$week <- as.Date(cut(denham$date,
                             breaks = "week",
                             start.on.monday = FALSE)) # changes weekly break point to Sunday

#Conversions of data
denham$inches <-(denham$feet*12) #feet x inches
denham$convin <- (77-denham$inches) #inches -
denham$cm <- (denham$convin*2.54) #converted inches x centimeters

denham$date<-as.POSIXlt(denham$date,format="%m/%d/%y %H:%M:%S")
denham <- within(denham, {
  day =   as.character(format(denham$date, "%m/%d/%y"))
  Jday =  as.integer(format(denham$date, "%j"))
  year =  as.integer(format(denham$date, "%Y"))
  month = as.integer(format(denham$date, "%m"))
  week =  as.integer(format(denham$date, "%W"))
})

#denham <- subset(denham, year>2008) #subset out after 2008 data because there is an error that shows and was also mentioned in the metadata

cmavmonths <- aggregate(cm ~ month+year, data = denham, mean) #mean of months and years
cmminmonth <- aggregate(cm ~ month+year, data = denham, "min") #min of months & years
cmmaxmonth <- aggregate(cm ~ month+year, data = denham, "max") #max of months & years

cmminyear <- aggregate(cm ~ year, data = denham, "min") #min of years
cmmaxyear <- aggregate(cm ~ year, data = denham, "max") #max of years

cmyear <- aggregate(cm ~ year, data = denham, mean) #averages years
cmavweek <- aggregate(cm ~ week+year, data = denham, mean) #averages of weeks & years
cmavday <- aggregate(cm ~ Jday+year, data = denham, mean) #averages of day & years
cmavdayweyr <- aggregate(cm ~ Jday+week+year, data = denham, mean) #averages of day, week, & years
cmav <-aggregate(cm ~ time+Jday+week+month+year, data = denham, mean) #averages of time, day, week, & years
cmavdaywemoyr <- aggregate(cm ~ Jday+week+month+year, data = denham, mean) #averages of day, week, month & years

inyear <- aggregate(convin ~ year, data = denham, mean) #averages years in inches
inmoyear <- aggregate(convin ~ month+year, data = denham, mean) #averages years in inches


#plot averages of years centimeters
ggplot(data = cmyear, aes(year, cm)) +
  geom_line(colour="purple")+ 
  ylim(200, -100)+
  geom_smooth(colour="green")+ 
  ylim(200, -100) +
  ggtitle("Year Averages") +
  theme(plot.title = element_text(lineheight=.8, face="bold"))

#plot averages of years inches
ggplot(data = inyear, aes(year, convin)) +
  geom_line(colour="purple")+ 
  ylim(100, -50)+
  geom_smooth(colour="green")+ 
  ylim(100, 0) +
  ggtitle("Year Averages") +
  ylab("Inches")+
  theme(plot.title = element_text(lineheight=.8, face="bold"))

#plot averages of months and years in centimeters
ggplot(data = cmavmonths, aes(month, cm, group = year)) +
  geom_line(aes(colour= factor(year)))+
  ggtitle("Averages of Months and Years")+
  theme(plot.title = element_text(lineheight=.8, face="bold"))

#plot averages of months and years in inches
ggplot(data = inmoyear, aes(month, convin, group = year)) +
  geom_line(aes(colour= factor(year)))+
  ggtitle("Averages of Months and Years")+
  ylab("Inches")+
  theme(plot.title = element_text(lineheight=.8, face="bold"))


#plot averages of months and years in centimeters ~ data gaps are noticable 
ggplot(data = cmavmonths, aes(month, cm)) +
  geom_line(colour="purple") +
  geom_smooth(colour="green") + 
  ylim(200, -50) +
  facet_wrap(~ year)+
  ggtitle("Averages of Months and Years")+
  theme(plot.title = element_text(lineheight=.8, face="bold"))

#plot averages of months and years in inches ~ data gaps are noticable 
ggplot(data = inmoyear, aes(month, convin)) +
  geom_line(colour="purple") +
  geom_smooth(colour="green") + 
  ylim(100, -0) +
  facet_wrap(~ year)+
  ggtitle("Averages of Months and Years")+
  ylab("Inches")+
  theme(plot.title = element_text(lineheight=.8, face="bold"))

#plot averages of months and years data
xyplot(cm ~ year | factor(month), data=cmavmonths, main='Averages of Months and Years', type=c('l', 'g'), as.table=TRUE, layout=c(2,6), xlab='month', ylab='cm')

#plot averages of months and years
ggplot(data = cmavmonths, aes(month, cm)) +
  geom_point(colour="purple")+ 
  ylim(200, -100)+facet_wrap(~year)+
  ggtitle("Averages of Months and Years")+
  theme(plot.title = element_text(lineheight=.8, face="bold"))



#Soil Moisture Numbers from NASIS
denham_sm=ldply(list.files(path="E:/Documents/GIS/Trainings/Stat_for_Soil_Survey/final_Project/nasis",pattern="csv",full.names=TRUE),function(filename) {
  dum=read.csv(filename)
  dum$filename=filename
  return(dum)
})

#subset wet column
denhamsm0 <- subset(denham_sm, Moisture.Status == "wet")

#Plot Low, RV, & High for Soil Moisture -needs a legend
#ggplot()+geom_point(data=denhamsm0, aes(Month, High), colour='red')+facet_wrap(~High)+
  #geom_point(data=denhamsm0, aes(Month, RV), colour='purple')+ facet_wrap(~High)+
  #geom_point(data=denhamsm0, aes(Month, Low), colour='green')+ facet_wrap(~High)+
 # ylim (200, 0)+ 
 # ylab("Low, RV, High")+
 # ggtitle("Soil Moisture Months from NASIS")+
 # theme(plot.title = element_text(lineheight=.8, face="bold"))




```

