---
output:
  html_document: default
---
# Pedon report
```{r enter soil series name}
# Set soil series
series <- "Treaty"

# Set percentiles
p <- c(0, 0.25, 0.5, 0.75, 1)
```


```{r load packages, include=FALSE}
# load libraries
library(aqp)
library(soilDB)
library(circular)
library(lattice)
library(RColorBrewer)
library(plyr)
library(ggplot2)
library(reshape2)
library(stringr)
library(knitr)
library(maps)

source("report_functions.R")
source(paste0("./genhz_rules/", series, "_rules.R"))

```


```{r fetch and format, load-data, echo=FALSE, warning=FALSE}
# load NASIS data
pedons <- fetchNASIS(nullFragsAreZero = TRUE)

h <- horizons(pedons)
h$hzname[is.na(h$hzname)] <- "missing"
na_idx <- is.na(pedons$genhz)
h[na_idx, "genhz"] <- as.character(sapply(h[na_idx, "hzname"], function(x) generalize.hz(x, ghr$n, ghr$p)))
horizons(pedons) <- h
pedons$hzdepm <- (pedons$hzdept + pedons$hzdepb)/2
genhz_med <- sort(tapply(pedons$hzdepm, pedons$genhz, median))
pedons$genhz <- factor(pedons$genhz, levels = names(genhz_med), ordered = TRUE)                                                                                                       

h <- horizons(pedons)
s <- site(pedons)
d <- diagnostic_hz(pedons)

h <- data.frame(lapply(h, na_replace), stringsAsFactors = FALSE)
s <- data.frame(lapply(s, na_replace), stringsAsFactors = FALSE)

l <- length(unique(h$peiid))

```


## Brief summary of pedon data

```{r Map of pedons and locations, echo=FALSE, results='asis'}
if (dim(s)[1] != 0) {
  s.sub <- s[complete.cases(s[c("x_std", "y_std")]), ]
  coordinates(s.sub) <- ~x_std + y_std
  plot(s.sub, pch = 16, main = "Map of pedons with coordinates")
  map("county", lwd = 0.5, add=T)
  map("state", lwd = 2, add = T)
  map.axes()
} else("no coordinates")
```


```{r format site data, results='asis', echo=FALSE}
# Site information
kable(subset(s, select = c("pedon_id", "taxonname", "tax_subgroup", "part_size_class", "pedon_type", "describer")), caption = "Summary of data in the selected set")
```


```{r, echo=FALSE}
cols <- brewer.pal(n = length(levels(pedons$genhz)), name = "Set1") 
hz.names <- levels(pedons$genhz)
pedons$genhz.soil_color <- cols[match(pedons$genhz, hz.names)] # assign a color to each generalized horizon label


idx <- pindex(pedons, 15)
  
for (i in unique(idx)){
  plot(pedons[idx == i], name = 'hzname', color = 'genhz.soil_color', label = 'pedon_id')
  title("Soil profile plots")
  legend('bottomleft', legend = hz.names, pt.bg = cols, pch = 22, horiz = TRUE, pt.cex = 2, text.width = 1)
  }
```


## Range in characteristics

### Summary of the soil surface

```{r surface rock fragments, echo=FALSE, results='asis'}
srf <- subset(s, select=c("surface_fgravel", "surface_gravel", "surface_cobbles", "surface_stones", "surface_boulders", "surface_flagstones", "surface_channers"))
names(srf) <- unlist(lapply(strsplit(names(srf), "surface_"), paste0, collapse = ""))
srf$total_srf <- srf$gravel + srf$cobbles + srf$stones + srf$boulders + srf$flagstones + srf$channers
srf$gravel <- srf$gravel - srf$fgravel


srf.lo <- melt(srf, measure.vars=c("total_srf", "fgravel", "gravel", "cobbles", "stones", "boulders", "channers", "flagstones"))
srf.5n <- ddply(srf.lo, .(variable), .fun = sum5n)

kable(srf.5n, align = "c", caption =  "Surface rock fragments (min, 25th, median, 75th, max)(n)")
 

if (sum(srf$total_srf, na.rm = T) != 0) {
  bwplot(variable ~ variable, data = srf.lo, ylab = "percent", main = "Boxplots of surface rock fragments")
  
  # qplot(variable, value, data = srf.lo, geom = "boxplot", ylab = "%", main = "Boxplots of surface rock fragments") + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
  }         
```


### Summary of diagnostic horizons and soil characteristics

```{r diagnostics, echo=FALSE, results='asis', warning=FALSE}
if (dim(d)[1] == 0)
{d <- data.frame(peiid = s$peiid)
d[c("diag_kind", "featdept", "featdepb")] <- list(diag_kind = as.character("missing"), featdept=as.integer(NA), featdepb = as.integer(NA))}

diag.thk <- ddply(d, .(peiid, diag_kind), summarize, thickness = sum(featdepb - featdept))
diag.lo <- melt(d, id.vars = "diag_kind", measure.vars = c('featdept', 'featdepb'))
diag.lo2 <- melt(diag.thk, id.vars = "diag_kind", measure.vars = 'thickness')

idx <- names(s) == "psctopdepth" | names(s) == "pscbotdepth"
names(s)[idx] <- c("featdept", "featdepb")
pscs.thk <- ddply(s, .(peiid), summarize, thickness = sum(featdepb - featdept))
pscs.thk <- data.frame(peiid = pscs.thk$peiid, variable = "thickness", value = pscs.thk$thickness)
pscs.lo <- melt(s, id.vars = "peiid", measure.vars = c('featdept', 'featdepb'))
pscs.lo <- rbind(pscs.lo, pscs.thk)
pscs.lo <- data.frame(diag_kind = "particle size control section", variable = pscs.lo$variable, value = pscs.lo$value)

diag.lo <- rbind(diag.lo, diag.lo2, pscs.lo)
diag.5n <- ddply(diag.lo, .(variable, diag_kind), .fun = sum5n)
diag.wi <- dcast(diag.5n, diag_kind ~ variable, value.var = 'range')

kable(diag.wi, align = "c", caption = "Depths and thickness of diagnostic horizons and features(min, 25th, median, 75th, max)(n)")


if (!all(is.na(diag.lo$value))) {
  bwplot(diag_kind ~ value | variable, data = diag.lo, scales =list(x="free"), main = "Boxplots of diagnostic horizon and feature depths", as.table = TRUE)
  
  # qplot(diag_kind, value, data = diag.lo, geom = "boxplot", ylab = "cm", main = "Boxplots of diagnostic horizon and feature depths") + facet_wrap(~variable, scales = "free") + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
}
```


### Summary of soil horizons

```{r hzname vs genhz, echo=FALSE, results='asis'}
hz_t <- addmargins(table(h$genhz, h$hzname))

idx <- pindex(hz_t, 15)

for (i in unique(idx)){
  print(kable(hz_t[, c(idx == i)], align = "c", digits = 0, caption = "Horizon designations vs generic horizon designations (counts)"))
  }

genhz.thk <- ddply(h, .(phiid, genhz), summarize, thickness=sum(hzdepb-hzdept))
genhz.lo <- melt(h, id.vars="genhz", measure.vars = c('hzdept', 'hzdepb'))
genhz.lo2 <- melt(genhz.thk, id.vars = "genhz", measure.vars = 'thickness')
genhz.lo <- rbind(genhz.lo, genhz.lo2)
genhz.5n <- ddply(genhz.lo, .(variable, genhz), .fun = sum5n)

kable(dcast(genhz.5n, genhz ~ variable, value.var = 'range'), align = "c", caption = "Depths and thickness of generic horizons (min, 25th, median, 75th, max)(n)")

genhz.lo$genhz <- factor(genhz.lo$genhz, levels = rev(levels(genhz.lo$genhz)))

bwplot(genhz ~ value | variable, data = genhz.lo, scales =list(x="free"), main = "Boxplots of horizon generic horizon depths and thickness", as.table = TRUE)

# qplot(genhz, value, data = genhz.lo, geom = "boxplot", ylab = "cm", main = "Boxplots of horizon generic horizon depths and thickness") + facet_wrap(~variable, scales = "free") + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

```{r genhz numeric variables, echo=FALSE, results='asis', warning=FALSE, fig.height=8, fig.width=8}
idx <- names(h) == "total_frags_pct_cal" | names(h) == "total_frags_pct"
names(h)[idx] <- c("fragvoltotc", "fragvoltot")
var <- c("fine_gravel", "gravel", "cobbles", "stones", "boulders", "paragravel", "paracobbles", "channers", "flagstones")
h[, var] <- lapply(h[var], as.integer)
h$gravel <- h$gravel-h$fine_gravel

h.lo <- melt(h, id.vars="genhz", measure.vars = c('clay', 'sand', 'fine_gravel', 'gravel', 'cobbles', 'stones', 'fragvoltot', 'phfield', 'd_value', 'd_chroma', 'm_value', 'm_chroma'))
h.5n <- ddply(h.lo, .(variable, genhz), .fun = sum5n)
h.wi <- dcast(h.5n, genhz ~ variable, value.var = 'range')

kable(h.wi[1:5], align = "c", caption = "Numeric variables by generic horizon (min, 25th, median, 75th, max)(n)")
kable(h.wi[c(1, 6:9)], align = "c")
kable(h.wi[c(1, 10:13)], align = "c")

h.lo$genhz <- factor(h.lo$genhz, levels = rev(levels(h.lo$genhz)))
n <- ceiling(length(levels(h.lo$variable))/4)

bwplot(genhz ~ value | variable, data = h.lo, scales=list(x="free"), main = "Box plots of numeric variables by generic horizon", as.table = TRUE, layout = c(4, n))

# qplot(genhz, value, data = h.lo, geom = "boxplot", ylab = "cm", main = "Boxplots of numeric variable by generic horizon") + facet_wrap(~variable, scales = "free") + theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```
</p>

```{r, echo=FALSE, results='asis'}
tc <- c("cos", "s", "fs", "vfs", "lcos", "ls", "lfs", "lvfs", "cosl", "sl", "fsl", "vfsl", "l", "sil", "si", "scl", "cl", "sicl", "sc", "sic", "c", "NA")
tc <- tc[tc %in% unique(h$texture_class)]
h$texture_class <- factor(h$texture_class, levels = tc)

kable(addmargins(table(h$genhz, h$texture_class, exclude = NULL)), digits = 0, caption = "Texture by generic horizon (counts)")

hz_tex <- addmargins(table(h$genhz, h$texture))
idx <- pindex(hz_tex, 15)

for (i in unique(idx)){
  print(kable(hz_tex[, c(idx == i)], align = "c", digits = 0, caption = "Tex Mod & Class by generic horizon (counts)"))
  }

```


```{r, echo=FALSE, results='asis'}
kable(addmargins(table(h$genhz, h$d_hue)), digits = 0, caption = "Dry hue by generic horizon (counts)")

kable(addmargins(table(h$genhz, h$m_hue)), digits = 0, caption = "Moist hue by generic horizon (counts)")
```


```{r, echo=FALSE, results='asis'}
h$effervescence[h$effervescence == "very slight"] <- "very.slight"
eff <- c(violent = "violent", strong = "strong", slight = "slight", very.slight = "very slight", none = "none", missing = "missing")
h$effervescence <- eff[h$effervescence]
h$effervescence <- factor(h$effervescence, levels = eff)

kable(addmargins(table(h$genhz, h$effervescence)), digits = 0, caption = "Effervescence by generic horizon (counts)")
```


## Geographic setting

```{r, echo=FALSE, results='asis', warning=FALSE}
vars <- c("elev_field", "slope_field")
morf <- subset(s, select = vars)
morf.lo <- melt(morf, measure.vars = vars)
morf.5n <- ddply(morf.lo, .(variable), .fun = sum5n)

if (!all(is.na(s$aspect_field))) {
  aspect <- subset(s, select = c("aspect_field"))
  aspect.lo <- melt(aspect, measure.vars = "aspect_field")
  aspect.lo$value <- circular(aspect.lo$value, template="geographic", units="degrees", modulo="2pi")
  aspect.5n <- ddply(aspect.lo, .(variable), .fun = sum5n)
  kable(rbind(morf.5n, aspect.5n), caption = "Elevation, slope gradient and aspect (min, 25th, median, 75th, max)(n)", align = "c")
} else(kable(morf.5n, caption="Elevation and slope gradient (min, 25th, median, 75th, max)(n)", align = "c")
)         

bwplot(~ value | variable, data = morf.lo, scales=list(x="free"), main = "Boxplots of elevation and slope gradient", as.table = TRUE)

# qplot("variable", value, data = morf.lo, geom = "boxplot", main = "Boxplots of elevation and slope gradient") + facet_wrap(~variable, scales = "free")

if (!all(is.na(s[c("pmorigin", "pmkind", "landform.string")]))){
  pm_comb <- factor(paste0(s$pmorigin, " ", s$pmkind))
  pm_land <- factor(s$landform.string)
  pm.lf <- addmargins(table(pm_comb, pm_land))
  kable(pm.lf, caption="Parent material vs landform (counts)")
  }

if (!all(is.na(s[c("shapedown", "shapeacross")]))) {
  s$shapedown <- factor(s$shapedown, levels=c("Convex", "Linear", "Concave", "missing"))
  s$shapeacross <- factor(s$shapeacross, levels=c("Convex", "Linear", "Concave", "missing"))
  kable(addmargins(table(s$shapedown, s$shapeacross)), caption = "Down slope (y-axis) vs across slope (x-axis) (counts)")
} 

if (!all(is.na(s[c("hillslope_pos", "drainagecl")]))) {
  s$hillslope_pos <- factor(s$hillslope_pos, levels=c("Summit", "Shoulder", "Backslope", "Footslope", "Toeslope", "missing"))
  s$drainagecl <- factor(s$drainagecl, levels= c("Excessivelly drained", "Well drained", "Somewhat excessively well drained", "Moderately well drained", "Somewhat poorly drained", "Poorly drained", "Very poorly drained", "Subaqueous drainage", "missing"))
  
  kable(addmargins(table(s$drainagecl, s$hillslope_pos)), digits = 0, caption = "Drainage class vs hillslope position (counts)")
}
```
