# Lab pedon report
```{r enter soil series name}
# Set soil series
series <- "Crosby"
```

```{r load packages, include=FALSE}
# load libraries
library(aqp)
library(soilDB)
library(reshape)
library(plyr)
library(knitr)
library(lattice)
library(maps)
library(RODBC)
library(ggplot2)
```

```{r fetch and format, load-data, echo=FALSE, warning=FALSE}
# source custom R functions
source(paste0("./genhz_rules/", series, "_rules.R"))

p <- c(0, 0.10, 0.5, 0.90, 1)

# load NASIS data
l <- fetchNASISLabData()
lh <- horizons(l)
lp <- site(l)
f <- fetchNASIS()
h <- horizons(f)
s <- site(f)

names(lh) <- unlist(strsplit(names(lh), "measured"))
lh$cec7Clay <- lh$cec7 / lh$claytot

for (i in seq(nrow(lh))){
  if (is.na(lh$hzname[i])) {lh$hzname[i] <-lh$hznameoriginal[i]}
}

lh$hzname[is.na(lh$hzname)] <- "missing"
lh$genhz <- generalize.hz(lh$hzname, ghr$n, ghr$p)

h$hzname[is.na(h$hzname)] <- "missing"
h$genhz <- generalize.hz(h$hzname, ghr$n, ghr$p)

na_replace <- function(x){
  if(class(x) == "character" | class(x) == "logical") {x <- replace(x, is.na(x) | x == "NA", "missing")} 
  else (x <-  x)
}

h <- data.frame(lapply(h, na_replace), stringsAsFactors = FALSE)

# Function
sum5n <- function(x) {
  variable <- unique(x$variable)
  precision.vars <- c('phfield', 'ph1to1h2o', 'ph01mcacl2', 'phoxidized', 'ph2osoluble', 'ecec', 'cec7', 'cecsumcations', 'sumbases', 'extracid', 'dbthirdbar', 'dbovendry', 'wthirdbarclod', 'wfifteenbar', 'wretentiondiffws', 'wfifteenbartoclay', 'cec7Clay')
  precision.table <- c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2)
  precision <- if(variable %in% precision.vars) precision.table[match(variable, precision.vars)] else 0
  n <- length(na.omit(x$value))
  ci <- data.frame(rbind(quantile(x$value, na.rm = TRUE, probs = p)))
  ci$range <- with(ci, paste0("(", paste0(round(ci, precision), collapse=", "), ")", "(", n, ")")) # add 'range' column for pretty-printing
  return(ci["range"])
}
```


## Brief summary of NCSS lab pedon data
```{r plot of pedons and locations, echo=FALSE}
if (dim(s)[1] != 0) {
  s.sub <- s[complete.cases(s[c('x_std', 'y_std')]),]
  coordinates(s.sub) <- ~x_std + y_std
  plot(s.sub, pch=16, main = "Map of pedons with coordinates")
  map("county", lwd = 0.5, add=T)
  map("state",lwd = 2, add=T)
  map.axes()
  }
```

```{r format site data, echo=FALSE, warnings=FALSE, results='asis'}
kable(subset(s, select = c("pedon_id", "taxonname", "tax_subgroup", "part_size_class", "pedon_type", "describer")))

plot(l, label="labpeiid")
title("Soil profile plots")
```


## Range in characteristics for NCSS pedon lab data
### Summary of soil profiles
Five number summary (min, 25th, median, 75th, max)(percentiles)
```{r, echo=FALSE, results='asis'}
# Summarize site data
lp.sub <- subset(lp, select=c("noncarbclaywtavg", "claytotwtavg", "le0to100", "wf0175wtavgpsc", "volfractgt2wtavg", "cec7clayratiowtavg"))
lp.lo <- melt(lp.sub, measure.vars=c("noncarbclaywtavg", "claytotwtavg", "le0to100", "wf0175wtavgpsc", "volfractgt2wtavg", "cec7clayratiowtavg"))
lp.5n <- ddply(lp.lo, .(variable), .fun = sum5n)

kable(cast(lp.5n, ~variable, value='range'), caption = "Summary of aggregate profile attributes")

if (any(!is.na(lp.lo$value))) {
  bwplot(variable ~ value, data=lp.lo, scales = list(x="free"), xlab = "percent", main = "Boxplots of aggregate profile attributes")
  }         

lp.lo1 <- melt(lp, id.vars="labpeiid", measure.vars = c("psctopdepth", "pscbotdepth"))
lp.thk <- ddply(lp, .(labpeiid), summarize, thickness = sum(pscbotdepth - psctopdepth))
lp.lo2 <- melt(lp.thk, id.vars = "labpeiid", measure.vars = "thickness")
lp.lo <- rbind(lp.lo1, lp.lo2)

lp.5n <- ddply(lp.lo, .(variable), .fun = sum5n)

kable(lp.5n, digits = 0, align = "c", caption = "Depths and thickness of particle size control section (min, 25th, median, 75th, max)(n)")

bwplot(factor(variable, levels=levels(lp.lo$variable)[length(levels(lp.lo$variable)):1]) ~ value|variable, data=lp.lo, scales=list(x="free"), xlab="cm", horizontal=T, main = "Boxplots of particle size control section depths and thickness")          

```


### Summary of soil horizons

```{r, echo=FALSE, results='asis'}
kable(addmargins(table(lh$genhz, lh$hzname)), digits = 0, caption = "Horizon designations vs generic horizon designations (counts)")


genhz.thk <- ddply(lh, .(labpeiid, genhz), summarize, thickness = sum(hzdepb - hzdept))
genhz.lo <- melt(genhz.thk, id.vars="genhz", measure.vars="thickness")

lh.lo <- melt(lh, id.vars = "genhz", measure.vars = c("hzdept", "hzdepb"))
lh.lo <- rbind(lh.lo, genhz.lo)
lh.5n <- ddply(lh.lo, .(variable, genhz), .fun = sum5n)
lh.c <- cast(lh.5n, genhz ~ variable, value = "range")

kable(lh.c, digits = 0, align = "c", caption = "Depths and thickness of generic horizons (min, 25th, median, 75th, max)(n)")

bwplot(factor(genhz, levels=levels(lh$genhz)[length(levels(lh$genhz)):1]) ~ value|variable, data=lh.lo, scales=list(x="free"), xlab="cm", horizontal=T, main = "Boxplots of horizon depths and thickness")          
```        


## Range in characteristics for generic horizons 
Five number summary (min, 25th, median, 75th, max)(percentiles) and total number of observations (n)

```{r, echo=FALSE, results='asis'}

lh.num <- lh[c(12:(ncol(lh)-4), ncol(lh)-1, ncol(lh))]
lh.num <- Filter(f = function(x) !all(is.na(x)), x = lh.num)
lh.lo <- melt(lh.num, id.vars="genhz", measure.vars=names(lh.num)[c(1:(ncol(lh.num)-1))])
lh.5n <- ddply(lh.lo, .(variable, genhz), .fun=sum5n)
lh.c <- cast(lh.5n, genhz~variable, value='range')

n <- ncol(lh.c)-1
interval <- 4
times <- ceiling(n/interval)
x <- rep(1:(times+1), each = interval, length.out = n)

for (i in seq(times)){
  print(kable(lh.c[c(TRUE, x == i)], align = "c"))
  }

nh <- ncol(lh.num)/2.5
```

```{r, echo=FALSE, fig.height=nh}

levels(lh.lo$genhz) <- levels(lh.lo$genhz)[length(levels(lh.lo$genhz)):1]

bwplot(genhz ~ value|variable, data = lh.lo, scales=list(x="free"), main = "Box plots of numeric variables by generic horizon")     

```

```{r, echo=FALSE, results='asis'}
kable(addmargins(table(lh$genhz, lh$lab_texcl)), digits = 0, caption = "Texture by generic horizon")

if (any(lh$stratextsflag != 0)){
  kable(addmargins(table(lh$genhz, lh$stratextsflag)), digits=0, caption = "Stratified flag by generic horizon")
  }

```


