---
  output: html_fragment
---
#### ABOUT THIS APP

The Region 11 Web App is a set of web applications which use [R](https://www.r-project.org/) to query information from [Soil Data Access](https://sdmdataaccess.nrcs.usda.gov/) or LIMS and assembles the data into a tables, graphs and reports.

#### How to Use

  1. Choose an application function by clicking on the corresponding menu item in the list on the sidebar to the left.
  2. Choose how to view the data.  You can view either a plot or data table for the Water Table and Organic Matter choices.  The Project Report and Project extent only contain one option for each.
  3. Choose a query method.  This is only needed if you choose the Water Table or Organic Matter choices.  You can query using any one of 3 methods:  Mapunit Key, National Mapunit Symbol, or Mapunit Name.  A choice list is provided.
  4. Enter your query.  Be sure to enter the proper format.  Each of the previously mentioned methods has a unique set of criteria in order to return data without error.
  5. Click the Submit button.  The query will not execute until this button is clicked.

#### LIMS Reports

This is a list of useful LIMS reports not easily found elsewhere.

#### Water Table

Use this data to learn more about the moisture in the soil.  The plot shows depths at which different moisture status typically occur throughout the year.  You also have the option of viewing either flooding frequency or ponding frequency in the plot by clicking the radio buttons.

#### Organic Matter

Use this data to learn more about the organic matter in the soil.  The plot shows how organic matter changes with depth.  There are no additional options for viewing this data.

#### Project Report

Use this data to compare project data with previously populated data.  There are no additional options for viewing this data.

#### Project Extent

Generate a map of the extent of a project.  This is useful for checking if a project extends beyond the intended area due to the use of a limited GIS dataset.

#### Long Range Plan

This Report generates plots for viewing acres, number of projects, and a timeline by office of all project plans for the next 10 years.

#### Interpretations

Generate a plot of all interpretations (limitations and suitabilities) for a given mapunit.  The data tables are also provided below.

#### Source Code

This menu item provides a link to a GitHub repository containing the computer code used in this application.

#### Submit App Issues

This menu item provides a link to the GitHub Repository issues page of the web app.  Submit an issue if one does not already exist by clicking the the green new issue button.  You can also submit an issue by sending an email to <john.hammerly@in.usda.gov>.