---
title: "examples"
author: "Stephen Roecker"
date: "May 22, 2017"
output: html_document
---

```{r reshaping data}
ownCloud <- "C:/Users/stephen/ownCloud/projects/201711FIN001_Glynwood/"
geodata <- "M:/geodata/"

gw <- read.csv(paste0(ownCloud, "Pts_gnbero_27Jan17.csv"))

library(reshape2)
library(tidyr)

soil_vals <- c("hzthk", "SolumDp", "CaCO3Dp", "claytotest", "firstbtclay", "mxvalue", "mxchroma")
geo_vals1 <- c("SlopeSIE", "ProfCrv", "PlanCrv", "relpos", "wetness")
vals <- c(soil_vals, geo_vals1)


# reshape with reshape2
gw_lo1 <- melt(gw, id.vars = "EroClassFD", measure.vars = vals)
gw_lo2 <- melt(gw, id.vars = "EroClassSIE", measure.vars = vals)


# reshape with base
gw_lo1_b <- reshape(gw[c("EroClassFD", vals)],
                    direction = "long",
                    timevar = "variable", times = vals,
                    v.names = "value", varying = vals 
                    )

gw_wi1_b <- reshape(test, 
                    direction = "wide",
                    timevar = "variable",
                    v.names = "value"
                    )
names(test2) <- gsub("value", "", names(test2))


# reshape with tidyr
idx <- which(names(gw) %in% vals)
gw_lo1 <- select(gw, EroClassFD, idx) %>%
  gather(key = variable, value = value, - EroClassFD)
gw_lo2 <- select(gw, EroClassSIE, idx) %>%
  gather(key = variable, value = value, - EroClassSIE)
```

```{r lattice}
library(soilDB)

test2 <- get_cosoilmoist_from_SDA_db(WHERE = "mukey = '406339'")
test <- subset(test2, !is.na(dept_r) & status == "Wet")

ggplot(test, aes(x = as.integer(month), y = dept_r, lty = status)) + geom_line() + ylim(150, 0)

panel_gribbon <- function(x, y, upper, lower, ..., 
                         fill, col, subscripts, font, fontface) {
  upper = upper[subscripts]
  lower = lower[subscripts]
  panel.polygon(c(x, rev(x)), c(upper, rev(lower)),
                col = fill, border = FALSE)
  }
panel_ribbon <- function(x, y, ...) {
  panel.superpose(x, y, ..., panel.groups = panel_gribbon)
  panel.xyplot(x, y, ...)
  }


xyplot(data = test, dept_r ~ as.integer(month) | compname, 
       groups = test$compname,
       upper = test$dept_l, lower = test$dept_h,
       type = "b", cex = 0.6, lty = 1:2,
       ylim = c(150, -5),
       grid = TRUE,
       panel = panel_ribbon
       )
```
