---
title: "Digital summaries of legacy pedon descriptions"
author: Stephen Roecker, Dylan Beaudette, Jay Skovlin, Skye Wills
output: word_document
---

# Abstract

Soil scientists have been collecting field and lab pedon descriptions for over a hundred years. Within the United States a large portion of this data is captured in the National Soil Information System (NASIS). While NASIS serves as a superb data repository, its analytical capabilities are limited, and thus we believe it's data is underutilized. Therefore we advocate the use of R, which can easily import data from NASIS and has custom functions designed for quantitative pedology, digital soil mapping, and soil physics. In conjunction with the Western Regional Cooperative Soil Survey Technology Committee we have developed html reports that provide standardized summaries and graphics of data commonly used for soil survey activities, such as Soil Data Join and Recorrelation, development of Official Series Descriptions and Soil Components, development of soil map units, and competing dissimilar soils. With little prior knowledge even R novices can quickly generate their own results. Examples can be viewed at, https://github.com/ncss-tech/soil-pit/tree/master/examples, where development is on-going.

# Introduction

In support of developing soil surveys over the last 100 years the National Cooperative Soil Survey (NCSS) has  amassed a substantial amount of legacy pedon data. This data consists of field estimates, observations, and laboratory measurements. Unlike the soil maps and their associated tabular datasets, pedon data represents unaggregated data (i.e. raw). This makes it invaluable resource for future updates to existing soil surveys. However because pedon data 


Since the advent of computer databases, a small portion of this data has been digitized and stored in several databases. Typically the most interest has been focused on the

Overtime the amount of legacy data has grown exponentially. 
