# set options and load packages
options(stringsAsFactors=F)

library(plyr)
library(dplyr)
library(stringr)
library(RCurl)
library(XML)
library(rgdal)
library(ggplot2)
library(lattice)
library(RColorBrewer)

source("C:/workspace/github/soil-pit/trunk/queries/kssl_queries.R")



goals <- goals_report(2012, "%25")
goals <- goals_report(2013, "%25")
goals <- goals_report(2014, "%25")
goals <- goals_report(2015, "%25")
goals <- goals_report(2016, "%25")

# WEB-PROJECT-Counties+with+approved+projects+DU
fy <- 2015

du2015 <- du_report(2015)
# du <- read.csv("report_digiting_unit_2015_08_11.csv")

du11 <- subset(du, State_Responsible == "Indiana")

ddply(du11, .(Office), summarize, nProjects = length(unique(Project_Name)))
```


```{r correlation report, echo=FALSE}
# WEB-Correlation_state_fy_ids

# all states
data(state)
st <- tolower(state.abb)
asymbol <- paste0(st, "%25")

# region 11 states
ssa <- readOGR(dsn = "M:/geodata/soils/soilsa_a_nrcs.shp", layer = "soilsa_a_nrcs", encoding = "ESRI Shapefile")@data
ssa$st <- substr(ssa$areasymbol, 1, 2)
st <- toupper(c("ia", "il", "in", "ks", "ky", "mi", "mn", "mo", "ne", "oh", "ok", "sd", "wi"))
asymbol <-  sort(ssa[ssa$st %in% st, "areasymbol"])

report2015 <- correlation_report(asymbol, 2015)
report2014 <- correlation_report(asymbol, 2014)
report2012 <- correlation_report(asymbol, 2012)
report2013 <- correlation_report(asymbol, 2013)
# corr <- read.csv("report_correlation_2015_09_02_spatial.csv")
# corr$region <- unlist(lapply(corr$Office, function(x) strsplit(x, "-")[[1]][1]))

corr11 <- subset(corr, grepl("11-", Office))
corr11 <- rename(corr11, c("Project_Name" = "pname", "New_Symbol" = "musym_corr", "Old_Musym2" = "old_musym_corr"))

ddply(corr11, .(Office), summarize, nProjects = length(unique(pname)))



# WEB-spatial_asym_uprojectid_dates

data(state)
# st <- tolower(state.abb)
ssa <- readOGR(dsn = "M:/geodata/soils/soilsa_a_nrcs.shp", layer = "soilsa_a_nrcs", encoding = "ESRI Shapefile")@data
st <- sort(unique(substr(ssa$areasymbol, 1, 2)))
# st <- paste0(c("in", "oh")) # Region 11
asymbol <- paste0(st, "%25")
start_date <- "10/01/2015"
finish_date <- "09/30/2016"
project_id <- "%25"

test <- sdjr_correlation(asymbol, project_id, start_date, finish_date)

sdjr_us <- group_by(test, region) %>% filter(projecttypename == "SDJR" & fy == "2016") %>% summarize(
  n_projects       = length(unique(projectiid)),
  n_musym          = length(unique(musym)),
  n_asymbol        = length(unique(areasymbol)),
  n_spatial        = sum(spatial_change, na.rm = T),
  approved_acres   = round(sum(muacres, na.rm = TRUE)),
  correlated_acres = round(sum(new_muacres, na.rm = TRUE)),
  pct_finished     = round((correlated_acres / approved_acres) * 100)) %>% 
  arrange(desc(correlated_acres))

dotplot(correlated_acres ~ region, data = sdjr_us)


sdjr_region11 <- group_by(test, office) %>% filter(region == "11" & projecttypename == "SDJR" & fy == "2016") %>% summarize(
  n_projects       = length(unique(projectiid)),
  n_musym          = length(unique(musym)),
  n_asymbol        = length(unique(areasymbol)),
  n_spatial        = sum(spatial_change, na.rm = T),
  approved_acres   = round(sum(muacres, na.rm = TRUE)),
  correlated_acres = round(sum(new_muacres, na.rm = TRUE)),
  pct_finished     = round((correlated_acres / approved_acres) * 100)) %>% 
  arrange(office)

sdjr_region11
ggplot(sdjr_region11, aes(x = pct_finished, y = correlated_acres, color = office)) + geom_point(cex = 5) + scale_colour_brewer(palette="RdYlBu")

sdjr_region11 <- as.data.frame(sdjr_region11)
color <- brewer.pal(11, "RdYlBu")
xyplot(correlated_acres ~ pct_finished, groups = office, data = sdjr_region11,
       type = c("p", "g"), cex = 2, pch = 16, col = color,  
       key = list(text = list(sdjr_region11$office), space = "right", 
                  points = list(pch = 16, col = color, cex = 2))
       )


r10_test <- group_by(test, region, projectname) %>% filter(projecttypename == "SDJR" & region == "10") %>% summarize(
  projecttypename = unique(projecttypename),
  goaled = sum(muacres, na.rm = T) * 0.2,
  acres = sum(muacres, na.rm = T))


test_idx <- grepl("^z|z$|^x|x$", test$new_musym) & test$musym != test$new_musym & test$new_musym != ""
head(test[test_idx, ])





st <- paste0(toupper(c("ia", "il", "in", "ks", "ky", "mi", "mn", "mo", "ne", "oh", "ok", "sd", "wi")), "%25")
leg <- legends_report(st)

```



