---
title: "sdjr_spatial_progress"
author: "Stephen Roecker"
date: "Monday, July 27, 2015"
output: html_document
---

library(RCurl)
library(XML)
library(plyr)
library(stringr)

options(stringsAsFactors=F)


```{r du report, echo=FALSE}
# WEB-PROJECT-Counties+with+approved+projects+DU
url_du <- "https://nasis.sc.egov.usda.gov/NasisReportsWebSite/limsreport.aspx?report_name=WEB-PROJECT-Counties+with+approved+projects+DU&fy=2015"
du_w <- getURLContent(url_du, ssl.verifypeer = F)

# This report has a funky structure, need to reformat
doc = htmlParse(du_w)
tableNodes <- getNodeSet(doc, "//tr")

l <- list()
for (i in 1:length(tableNodes)){
  l[[i]] <- rbind(readHTMLList(tableNodes[[i]]), stringsAsFactors = F)
}
du_p <- ldply(l)

# Rename, subset and find spatial changes
names(du_p) <- du_p[1, ] # append first row to column names
du_p <- du_p[-1, ] # remove the first row
names(du_p) <- unlist(lapply(names(du_p), function(x) paste(strsplit(x, " ")[[1]], collapse = "_"))) # reformat column names
du_r11 <- subset(du_p, grepl("11-", Office)) # subset Region 11
du_r11 <- du_p

ddply(du_r11, .(Office), summarize, nProjects = length(unique(Project_Name)))

# write.csv(du_r11, file = paste0("du_report_region11_", format(Sys.time(), "%Y_%m_%d"), ".csv"))
write.csv(du_r11, file = paste0("du_report_regions_", format(Sys.time(), "%Y_%m_%d"), ".csv"))
```


```{r correlation report, echo=FALSE}
# WEB-Correlation_state_fy_ids
url_cor <- "https://nasis.sc.egov.usda.gov/NasisReportsWebSite/limsreport.aspx?report_name=WEB-Correlation_state_fy_id&asymbol=%25&fy=2015" # Works ... Thanks Kevin
cor_w <- getURLContent(url_cor, ssl.verifypeer = F)
cor_p <- readHTMLTable(cor_w, stringsAsFactors = F)[[1]]

# Rename, subset and find spatial changes
names(cor_p) <- unlist(lapply(names(cor_p), function(x) strsplit(x, "\n")[[1]][2]))
names(cor_p) <- sapply(names(cor_p), function(x) paste(strsplit(x, " ")[[1]], collapse = "_"))

cor_r11 <- subset(cor_p, grepl("10-", Office))
cor_r11 <- cor_p
cor_r11$Region <- sapply(cor_p$Office, function(x) strsplit(x, "-")[[1]][1])

z_error <- function(old, new){
  n <- nchar(old)
  first <- substr(old, 1, 1)
  last <- substr(old, n, n)
  new2 <- old
  
  if (old != new & (first == "z" | last == "z")) {new2 <- paste0(strsplit(old, "z")[[1]], collapse = "")}
  else old
  if (old != new & (first == "x" | last == "x")) {new2 <- paste0(strsplit(old, "x")[[1]], collapse = "")}
  else old
  if (old == new) new2 <- new
  
  return(new2)
}

cor_r11$Old_Musym2 <- mapply(z_error, old = cor_r11$Old_Musym, new = cor_r11$New_Symbol)


cor_r11$spatial <- cor_r11$New_lmuiid != cor_r11$Old_lmuiid | cor_r11$New_Symbol != cor_r11$Old_Musym2
cor_r11$spatial_mukey <- cor_r11$New_lmuiid != cor_r11$Old_lmuiid
cor_r11$spatial_musym <- cor_r11$New_Symbol != cor_r11$Old_Musym2

cor_s <- subset(cor_r11, spatial == TRUE)
ddply(cor_s, .(Office), summarize, nProjects = length(unique(Project_Name)))

# write.csv(cor_s, file = paste0("cor_report_region11_", format(Sys.time(), "%Y_%m_%d"), ".csv"))
write.csv(cor_s, file = paste0("cor_report_regions_", format(Sys.time(), "%Y_%m_%d"), ".csv"))
```



