# Report of changes requiring SSURGO recertification

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# These figures don't compare with Alena's spreadsheets. Her spreadsheets have additional counties that aren't captured in the Project Record.
# This assumes no changes have been made to the ORIG columns, could run Alena's qa against an unedited copy.

options(stringsAsFactors = F)

library(foreign)
library(knitr)
library(plyr)
library(RCurl)
library(XML)

source("C:/workspace/github/soil-pit/trunk/queries/kssl_queries.R")

fy <- 2016
region <- 11
office <- "11-GAL"
mupolygon <- read.dbf("M:/geodata/project_data/11GAL/RTSD_MLRA_-_Mapunit_Polygon_-_Gallatin_FY16_edits.dbf", as.is = TRUE)
owners <- read.csv("M:/geodata/soils/SSA_Regional_Ownership_MASTER_MLRA_OFFICE.csv")

# data(state)
# st <- paste0(tolower(state.abb), "%25")
st <- paste0(toupper(c("ia", "il", "in", "ks", "ky", "mi", "mn", "mo", "ne", "oh", "ok", "sd", "wi")), "%25")
# ssa <- readOGR(dsn = "M:/geodata/soils/soilsa_a_nrcs.shp", layer = "soilsa_a_nrcs", encoding = "ESRI Shapefile")@data
# st <- sort(unique(substr(ssa$areasymbol, 1, 2)))

# goals <- goals_report(fy, paste0(region, "-%25"))
goals <- read.csv("C:/workspace/report_goals_fy16_2016_08_31.csv")

# corr <- sdjr_correlation(asymbol, project_id, start_date, finish_date)
corr <- read.csv("C:/workspace/report_correlation_fy2016_AK%25_WY%25_2016_08_31.csv")
test <- substr(corr$musym, 1, nchar(corr$musym)-1)
corr$musym <- with(corr, ifelse(musym != test 
                                & grepl("{1}[zxaZS]", musym), 
                                test, musym))
corr$musym <- with(corr, ifelse(musym != new_musym 
                                & !grepl("^[zxaZ]|[zxaZS]$|\\+$|_old$", musym), 
                                musym, new_musym))

# legend <- legends_report(st)
legends <- read.csv("C:/workspace/report_legends_2016_08_31.csv")
```

```{r, summarize geodatabase tabular changes, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}

# WEB-MLRA_Goals_Progress

goals_sub <- goals[goals$ss_office == office, ]
goals_summary <- ddply(goals_sub, .(ss_office), summarize,
  n_projects = length(unique(project_name)),
  goaled = sum(goaled), 
  claimed = sum(reported),
  progress = goaled / claimed * 100
  )

kable(goals_summary, caption = "Number or SDJR projects per SS Office")


# Correlation report (completed spatial changes in NASIS)

corr_sub <- corr[corr$office %in% office &
                   !is.na(corr$new_musym)
                   , ]
corr_summary <- ddply(corr_sub, .(office), summarize,
                      n_projects = length(unique(projectiid)),
                      acres = sum(muacres) * 0.2
                      )
kable(corr_summary, caption = "Number of completed SDJR changes")


corr_sub <- corr[corr$office %in% office &
                   !is.na(corr$new_musym) &
                   corr$spatial_change == TRUE
                 , ]
corr_summary <- ddply(corr_sub, .(office), summarize,
                      n_projects = length(unique(projectiid)),
                      acres = sum(muacres) * 0.2
                      )
kable(corr_summary, caption = "Number of completed spatial changes")


vars <- c("office", "projectname", "areasymbol", "new_musym")
nasis_qa <- ddply(corr_sub, vars, summarize, 
                  n_musym = length(unique(musym)),
                  musym_c = paste0(unique(musym), collapse=", ")
                  )
nasis_qa2 <- ddply(corr_sub, vars, summarize,
                   musym = unique(musym)
                   )
nasis_qa3 <- merge(nasis_qa2, nasis_qa, by = vars, all.x = TRUE)


# Geodatabase report (completed spatial changes in geodatabase)

idx <- names(mupolygon) %in% c("MUSYM", "ORIG_MUSYM", "Editor_Fie")
names(mupolygon)[idx] <- c("new_musym", "musym", "editor")
names(mupolygon) <- tolower(names(mupolygon))

idx <- with(mupolygon, (musym != new_musym & musym != "") | editor != "")
mupolygon_edits <- mupolygon[idx, ]

vars <- c("areasymbol", "new_musym")
geo_qa <- ddply(mupolygon_edits, vars, summarise,
                n_polygons = length(musym),
                acres = round(sum(shape_area*0.000247), 0),
                n_musym = length(unique(musym)),
                musym_c = paste0(unique(musym), collapse=", ")
                )
geo_qa2 <- ddply(mupolygon_edits,vars, summarize,
                 musym = unique(musym)
                 )
geo_qa3 <- merge(geo_qa2, geo_qa, by = vars, all.x = TRUE)


write.csv(geo_qa2, 
          paste0(
            "C:/workspace/report_spatial_geo_qa_", 
            office, 
            "_", 
            format(Sys.time(), "%Y_%m_%d"), 
            ".csv"), 
          row.names = FALSE)
```

```{r, QA checks, echo=FALSE}
# QA checks
vars <- c("areasymbol", "musym", "new_musym")
qa <- merge(nasis_qa3, geo_qa3, by = vars, all = TRUE) # match geo_qa2 to nasis_qa2
# qa2 <- join(nasis_qa2, geo_qa2, by = key, type = "full") # match geo_qa2 to nasis_qa2

leg_key <- with(legends, paste0(mapunit_symbol, "_", area_symbol))
qa_key <- with(qa, paste0(new_musym, "_", areasymbol))

qa <- transform(qa, 
                in_project = !is.na(projectname),
                in_geodatabase = !is.na(n_polygons),
                in_legend = qa_key %in% leg_key # need to separate out this check, cuz 
                )

qa_sub <- subset(qa, musym != new_musym & !grepl("^[zxaZ]|[zxaZS]$|\\+$|_old$", musym))

qa_project <- subset(qa_sub, in_project == FALSE)
qa_geo <- subset(qa_sub, in_geodatabase == FALSE)
qa_leg <- subset(qa, in_legend == FALSE)

if (dim(qa_project)[1] != 0) {
  kable(qa_project, caption = "SDJR Project changes missing from the Geodatabase - Missing values (NA) need to be either added/removed from NASIS or the RTSD geodatabase, Otherwise they maybe splits that need to be relinked to a new additional mapunit.")
} else cat("SDJR Projects in NASIS match the Geodatabase")

if (dim(qa_geo)[1] != 0) {
  kable(qa_geo, caption = "Geodatabase changes missing from the SDJR Projects in NASIS - Missing values (NA) need to be either added/removed from NASIS or the RTSD geodatabase, Otherwise they maybe splits that need to be relinked to a new additional mapunit.")
} else cat("Geodatabase matches the SDJR Projects in NASIS")

if (dim(qa_leg)[1] != 0) {
  kable(qa_leg, caption = "Geodatabase musym missing from the legend")
  } else cat("Legends in NASIS match the Geodatabase")

write.csv(qa, paste0("C:/workspace/report_spatial_qa_", office, "_", format(Sys.time(), "%Y_%m_%d"), ".csv"))

# id <- match(nasis_qa2$key, geo_qa2$key, incomparables=TRUE)
# nasis_mis <- unique(nasis_qa2$key[is.na(id)]) # key present in NASIS, but missing from the geodatabase
# length(nasis_mis); print("number of musym missing from the RTSD geodatabase")

# id <- match(geo_qa2$key, nasis_qa2$key, incomparables=TRUE)
# geo_mis <- unique(geo_qa2$key[is.na(id)]) # key present in the geodatabase, but missing from NASIS
# length(geo_mis); print("number of musym missing from NASIS")

```

```{r, adjacent regions, echo=FALSE}
corr_owners <- merge(qa, owners, by.x = "areasymbol", by.y = "AREASYMBOL", all.x = TRUE)

outside <- subset(corr_owners, 
                  !(corr_owners$Region %in% region), 
                  select = c(Region, office, areasymbol, projectname, new_musym, musym, n_polygons, acres, in_legend))

if (dim(outside)[1] != 0) {
  kable(outside, caption = "MUSYM that need updating outside of Region")
  } else cat(c("No changes from", office, "to surrounding MLRA offices"))


# Need Check for changes from other regions
```